# Exercise - List

1) Create  any random list and assign it to a variable dummy_list

In [0]:
import random

In [0]:
dummy_list = [random.randrange(10) for i in range(11)]

2) print dummy_list

In [0]:
print(dummy_list)

[5, 2, 2, 8, 3, 1, 8, 6, 4, 0, 4]


3) Reverse dummy_list and print

In [0]:
print(list(reversed(dummy_list)))

[4, 0, 4, 6, 8, 1, 3, 8, 2, 2, 5]


4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]

In [0]:
#Adding (element wise addition) with original dummy_list (not reversed)
dummy_list = [a+b for a,b in zip(dummy_list,dummy_list_2)]
print(dummy_list)

[7, 202, 18, 12, 4, 1, 17.45, 51.67, 94, 12.01, 16.02]


5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values. 

In [0]:
dummy_dict = {}
[dummy_dict.update({i:dummy_list.count(i)}) for i in dummy_list]

[None, None, None, None, None, None, None, None, None, None, None]

6) print dummy_dict

In [0]:
print(dummy_dict)

{7: 1, 202: 1, 18: 1, 12: 1, 4: 1, 1: 1, 17.45: 1, 51.67: 1, 94: 1, 12.01: 1, 16.02: 1}


7) Sort dummy_list in ascending order as well as descending order and print the changed lists 

In [0]:
dummy_list_asc = sorted(dummy_list)
print(dummy_list_asc)
dummy_list_desc = sorted(dummy_list, reverse=True)
print(dummy_list_desc)

[1, 4, 7, 12, 12.01, 16.02, 17.45, 18, 51.67, 94, 202]
[202, 94, 51.67, 18, 17.45, 16.02, 12.01, 12, 7, 4, 1]


8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
print('Before',dummy_list)

Before [7, 202, 18, 12, 4, 1, 17.45, 51.67, 94, 12.01, 16.02]


In [0]:
x=202
dummy_list.remove(x)
print('After',dummy_list)

After [7, 18, 12, 4, 1, 17.45, 51.67, 94, 12.01, 16.02]


In [0]:
x = 200
# Let's play: try the same with something which is not in the list to get the ValueError
dummy_list.remove(x)


ValueError: ignored

9) Remove the item at position x. x is any random integer

In [0]:
print('Before',dummy_list)
x=2
dummy_list.pop(x)
print('After',dummy_list)

Before [7, 18, 12, 4, 1, 17.45, 51.67, 94, 12.01, 16.02]
After [7, 18, 4, 1, 17.45, 51.67, 94, 12.01, 16.02]


In [0]:
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get
x=len(dummy_list) + 1
dummy_list.pop(x)
print(dummy_list)

IndexError: ignored

10) Let's clean everything clear the list and then print

In [0]:
print('Before',dummy_list)
dummy_list.clear()
print('After',dummy_list)

Before [7, 18, 4, 1, 17.45, 51.67, 94, 12.01, 16.02]
After []


# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [0]:
n = int(input("n: "))
arr = np.tile([1,2,3],3)
print(arr)

n: 3
[1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [0]:
arr = list(range(1,2*10,2))
print(arr, len(arr))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19] 10


4) Find intersection of a and b

In [0]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [0]:
np.intersect1d(a,b)

array([2, 4])

5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10)

In [0]:
print(a.reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [0]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
#to array
arr = np.array(a)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#to list
lst = arr.tolist()
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [0]:
np.pad(np.zeros((10,10)), 1 ,'constant',constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [0]:
h=int(8/2)
w=int(8/2)
np.tile(np.eye(2),(h,w))
#whats slicing+striding approach?

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# Numpy Examples

## What is numpy?

#### Python has built-in:

-  containers: lists (costless insertion and append), dictionnaries (fast lookup)
-  high-level number objects: integers, floating point

#### Numpy is:

 - extension package to Python for multidimensional arrays
 - closer to hardware (efficiency)
 - designed for scientific computation (convenience)


#### Import numpy



In [0]:
import numpy as np

### Uncomment Print statement and run each cell to see the output

#### Create numpy arrays


In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


#### Some basic functions for creating arrays. Print all the defined arrays and see the results.

In [3]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.86638718 0.22462005]
 [0.55309322 0.25885683]]


#### Execute and understand :)

In [5]:
a  =  np.arange(10)
b  =  np.linspace(0,10, num=6)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


#### Array Indexing

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


#### Slicing

In [7]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Aritmetic operations

In [8]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


#### Using Boolean Mask

In [9]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array


[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [10]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Swapping two columns in a 2d numpy array

In [11]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Swapping two rows in a 2d numpy array

In [13]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
