1) Create any random list and assign it to a variable dummy_list


In [0]:
dummy_list = [1,2,3,4,5]

2) print dummy_list

In [0]:
print(dummy_list)

[1, 2, 3, 4, 5]


3) Reverse dummy_list and print



In [0]:
dummy_list.reverse()
print(dummy_list)

4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]

for i in dummy_list_2:
  dummy_list.append(i)
  
print(dummy_list)

5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values.



In [0]:
dummy_dict = {}
for i in dummy_list:
    a=0
    for k in dummy_list:
        if i==k:
            a +=1
    dummy_dict[i] = a

6) print dummy_dict



In [0]:
print(dummy_dict)

7) Sort dummy_list in ascending order as well as descending order and print the changed lists



In [0]:
dummy_list.sort()
print(dummy_list)
dummy_list.reverse()
print(dummy_list)

8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
for i in dummy_list:
    if i==x:
        dummy_list.remove(i)
        break
  

9) Remove the item at position x. x is any random integer



In [0]:
x=9
del dummy_list[x]

10) Let's clean everything clear the list and then print



**Numpy Exercises**


1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [4]:
import numpy as np
x = np.linspace(-1.3,25,64)


array([-1.3       , -0.88253968, -0.46507937, -0.04761905,  0.36984127,
        0.78730159,  1.2047619 ,  1.62222222,  2.03968254,  2.45714286,
        2.87460317,  3.29206349,  3.70952381,  4.12698413,  4.54444444,
        4.96190476,  5.37936508,  5.7968254 ,  6.21428571,  6.63174603,
        7.04920635,  7.46666667,  7.88412698,  8.3015873 ,  8.71904762,
        9.13650794,  9.55396825,  9.97142857, 10.38888889, 10.80634921,
       11.22380952, 11.64126984, 12.05873016, 12.47619048, 12.89365079,
       13.31111111, 13.72857143, 14.14603175, 14.56349206, 14.98095238,
       15.3984127 , 15.81587302, 16.23333333, 16.65079365, 17.06825397,
       17.48571429, 17.9031746 , 18.32063492, 18.73809524, 19.15555556,
       19.57301587, 19.99047619, 20.40793651, 20.82539683, 21.24285714,
       21.66031746, 22.07777778, 22.4952381 , 22.91269841, 23.33015873,
       23.74761905, 24.16507937, 24.58253968, 25.        ])

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

3) Create an array of the first 10 odd integers.


In [48]:
y = np.arange(1,10,2)
y

array([1, 3, 5, 7, 9])

4) Find intersection of a and b


In [5]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

5) Reshape 1d array a to 2d array of 2X5


In [11]:
a = np.arange(10)
B = np.reshape(a, (2, 5))
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

6) Create a numpy array to list and vice versa


In [47]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.array(a).tolist()
np.asarray(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.


In [25]:
m = np.zeros((10,10))
m[0,:] = 1
m[:,0] = 1
m[9,:] = 1
m[:,9] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.


In [45]:
n = np.zeros((8,8))


n[::2,::2] = 1
n[1::2,1::2] = 1

n

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])