[View in Colaboratory](https://colab.research.google.com/github/AGCreates/Assignment-2/blob/AGCreates/AGCreates.ipynb)

In [2]:
import random
dummy_list = [x for x in range (10)]
print ("Dummy List", dummy_list)
dummy_list.reverse()
print (" Dummy List Reversed", dummy_list)
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list= dummy_list + dummy_list_2
print("Dummy List after addition ", dummy_list)

dummy_list_freq = []
dummy_list_unique = []
for x in dummy_list:
      if x not in dummy_list_unique:
             dummy_list_unique.append(x)
print (" Dummy List Unique ",dummy_list_unique)

for x in (dummy_list_unique):
  counter=0
  for y in (dummy_list):
    if x==y:
      counter= counter+1
  dummy_list_freq.append(counter)
  
dummy_dict = dict()
for i in range (len(dummy_list_unique)):
       for j in range (len(dummy_list_freq)):
              if i == j:  dummy_dict[dummy_list_unique[i]] = dummy_list_freq[j]
print ("Dummy Dictionary", dummy_dict)
dummy_list.sort()
print ("Dummy List Sorted Ascending Order", dummy_list)
dummy_list.reverse()
print ("Dummy List Sorted Descending Order",dummy_list)  
dummy_list.remove(200)
print ("Dummy List Sorted After removing x= 200", dummy_list)
index_remove = random.randint(0, len(dummy_list)-1)
print ("Removing the value at radom index ", index_remove, " which is ")
dummy_list.pop(index_remove)
print ("Dummy List after removal of value at random index ", dummy_list)
print ("Cleared Dummy List ", dummy_list.clear())

Dummy List [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
 Dummy List Reversed [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Dummy List after addition  [9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
 Dummy List Unique  [9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 200, 16, 9.45, 45.67, 90, 12.01, 12.02]
Dummy Dictionary {9: 1, 8: 1, 7: 1, 6: 1, 5: 1, 4: 2, 3: 1, 2: 2, 1: 2, 0: 2, 200: 1, 16: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}
Dummy List Sorted Ascending Order [0, 0, 1, 1, 2, 2, 3, 4, 4, 5, 6, 7, 8, 9, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
Dummy List Sorted Descending Order [200, 90, 45.67, 16, 12.02, 12.01, 9.45, 9, 8, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0]


In [5]:
import numpy as np

#Numpy examples have been tried out but haven not been added here.
#This part consists of the Numpy Exercise only 


unisub = np.linspace(-1.3, 2.5, 64)
print ("Uniform Subdivision: \n", unisub) 

n = 8
cyc= np.array([1, 2, 3])
cyc = np.resize(cyc, 3 * n) 
print("Cyclic Pattern \n", cyc) 

oddarr = np.arange(1, 2 * 10, 2)
print (" First 10 odd int array:\n", oddarr) 


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

intersect = np.intersect1d(a, b)
print("Intersection array \n", intersect)

a = np.arange(10)
        
a = a.reshape(2, 5)
        
print("Reshaped Array \n",  a)


a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
      
a = np.array(a)
print("List to Numpy Array: \n", a)
     
a= list(a)
print("Numpy Array to List: \n", a)




n = 10
arr = np.zeros(shape = (n, n))
print("Array of Zeroes: \n", arr)
print()
arr[n - 1, :] = np.ones(n)
arr[:, 0] = np.ones(n)
arr[:, n - 1] = np.ones(n)
arr[0, :] = np.ones(n)
print("Array of Zeroes bounded by 1:\n", arr)
  

n=8 
      
print("Checkerboard:")
x = np.zeros((n, n), dtype = int) 
x[1::2, ::2] = 1
x[::2, 1::2] = 1
      
for i in range(n): 
    for j in range(n): 
        print(x[i][j], end= " ",)  
    print()  
  

Uniform Subdivision: 
 [-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]
Cyclic Pattern 
 [1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 First 10 odd int array:
 [ 1  3  5  7  9 11 13 15 17 19]
Intersection array 
 [2 4]
Reshaped Array 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Lis