In [2]:
dummy_list =[1,2,3,4]
print(dummy_list)
dummy_list= [1,2,3,4]
dummy_list.reverse()
print(dummy_list)
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list= [1,2,3,4]
dummy_list.append(dummy_list_2)
print(dummy_list)
dummy_dict= {"1":12, "2":24, "3":36, "4":48}
print(dummy_dict)
dummy_list= [1,2,3,4]
dummy_list.sort()
dummy_list.sort(reverse=True)
print(dummy_list)
x = 200
dummy_list= [1,2,3,4]
dummy_list.remove(x)
print(dummy_list)
x = 200
dummy_list= [1,2,3,4]
dummy_list.remove(x)
print(dummy_list)
dummy_list= [1,2,3,4]
dummy_list.clear()
print(dummy_list)

[1, 2, 3, 4]
[4, 3, 2, 1]
[1, 2, 3, 4, [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]]
{'1': 12, '2': 24, '3': 36, '4': 48}
[4, 3, 2, 1]


ValueError: ignored

In [4]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(type(a))
b = np.array([[1,2,3],[4,5,6]])   
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))
print('a', a)
print('b', b)
print('c',c)
print('d',d)
print('e',e)
a  = np.arange(10)
b  = np.linspace(0,10, num=6)
print(a)
print(b)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)
b[0, 0] = 77  
print(a[0, 1])
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    
row_r2 = a[1:2, :]  
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
b = np.arange(10)
print(b)
mask = b%2!=0 
print(mask)
print(b[mask])
modified_b = b
modified_b[mask] = -1
print(modified_b)
a = np.arange(9).reshape(3,3)
print(a)
print(a[:, [1,0,2]])
a = np.arange(9).reshape(3,3)
print(a)
print(a[[1,0,2], :])


[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4
a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.12394909 0.93245098]
 [0.43223236 0.24586139]]
[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]
[[2 3]
 [6 7]]
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
10
[4 6]
[3 7]
[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [6]:
import numpy as np
a= np.array([[1,2,3], [1,2,3]])
print(a)
def odd_numbers(numbers) :
    a = []
    for i in range(0,len(numbers)-1) :
        if i % 2 != 0 :
            a.append(i)
    return a
l = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
print(odd_numbers(l))
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
lst = [value for value in a if value in b]
print(lst)
a = np.arange(10).reshape(5,2)
print(a)
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(b)
c= b.tolist()
print(c)
a= np.ones(shape=(10,10))
a[1:-1,1:-1] = 0
print(a)
a= np.zeros(shape=(10,10))
a8=a[1:8,1:8]
for row in range(len(a8)-1, -1, -1):
    for col in range(len(a8[0])-1, -1,-1):
        if (row+col)%2==0:
            a8[row][col]=1
print(a8)

[[1 2 3]
 [1 2 3]]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[2, 2, 4, 4]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]]
