# Exercise - List

1) Create  any random list and assign it to a variable dummy_list

In [0]:
dummy_list=['friends','sherlock','suits','narcos','office']

2) print dummy_list

In [3]:
print(dummy_list)

['friends', 'sherlock', 'suits', 'narcos', 'office']


3) Reverse dummy_list and print

In [4]:
dummy_list.reverse()
print(dummy_list)

['office', 'narcos', 'suits', 'sherlock', 'friends']


4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [5]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)

['office', 'narcos', 'suits', 'sherlock', 'friends', 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values. 

In [0]:
dummy_dict={x:dummy_list.count(x) for x in dummy_list}

6) print dummy_dict

In [7]:
print(dummy_dict)

{'office': 1, 'narcos': 1, 'suits': 1, 'sherlock': 1, 'friends': 1, 2: 1, 200: 1, 16: 1, 4: 1, 1: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


7) Sort dummy_list in ascending order as well as descending order and print the changed lists 

8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
dummy_list.remove(x)
# Let's play: try the same with something which is not in the list to get the ValueError

In [10]:
x=100
dummy_list.remove(x)

ValueError: ignored

9) Remove the item at position x. x is any random integer

In [0]:
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get
x=2
del dummy_list[x]

10) Let's clean everything clear the list and then print

In [13]:
dummy_list.clear()
print (dummy_list)

[]


# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [0]:
a=np.arange(12).reshape(4,3)

3) Create an array of the first 10 odd integers.

In [7]:
a=np.arange(20)
mask=a%2!=0
print(a[mask])

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [12]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10).reshape(2,5)

6) Create a numpy array to list and vice versa

In [15]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.array(a).tolist()


[1, 2, 3, 4, 5, 6, 7, 8, 9]

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [33]:
a=np.zeros(100).reshape(10,10)
a[:,:]=1
b=a[1:9,1:9]
b[:,:]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [41]:
a=np.zeros(64).reshape(8,8)
b=a[1::2,::2]=1
b=a[::2,1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
