In [0]:
dummy_list=[]
l1=[2,4,6,1,5]
dummy_list=l1

In [6]:
dummy_list=[2,4,6,1,5]
print(dummy_list)

[2, 4, 6, 1, 5]


In [3]:
dummy_list.reverse()
print(dummy_list)

[5, 1, 6, 4, 2]


In [8]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list=dummy_list+dummy_list_2
print(dummy_list)

[6, 5, 4, 2, 1, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_dict={}
dummy_dict[0]=1
dummy_dict[1]=dummy_list.count(1)
dummy_dict[2]=dummy_list.count(2)
dummy_dict[4]=dummy_list.count(4)
dummy_dict[5]=dummy_list.count(5)
dummy_dict[6]=dummy_list.count(6)
dummy_dict[9.45]=dummy_list.count(9.45)
dummy_dict[12.01]=dummy_list.count(12.01)
dummy_dict[12.02]=dummy_list.count(12.02)
dummy_dict[16]=dummy_list.count(16)
dummy_dict[45.67]=dummy_list.count(45.67)
dummy_dict[90]=dummy_list.count(90)
dummy_dict[200]=dummy_list.count(200)

In [10]:
print(dummy_dict)

{0: 1, 1: 2, 2: 2, 4: 2, 5: 1, 6: 1, 9.45: 1, 12.01: 1, 12.02: 1, 16: 1, 45.67: 1, 90: 1, 200: 1}


In [11]:
dummy_list.sort()
print(dummy_list)
dummy_list.reverse()
print(dummy_list)

[0, 1, 1, 2, 2, 4, 4, 5, 6, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 6, 5, 4, 4, 2, 2, 1, 1, 0]


In [12]:
x=200
dummy_list.remove(x)
print(dummy_list)

[90, 45.67, 16, 12.02, 12.01, 9.45, 6, 5, 4, 4, 2, 2, 1, 1, 0]


In [13]:
i=3
dummy_list.pop(i)
print(dummy_list)

[90, 45.67, 16, 12.01, 9.45, 6, 5, 4, 4, 2, 2, 1, 1, 0]


In [14]:
dummy_list.clear()
print(dummy_list)

[]


In [16]:
import numpy as np
a=np.linspace(-1.3,2.5,64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [18]:
x = np.array([1.0, 2.0, 3.0])
y = np.resize(x, 15)
print(y)

[1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [19]:
a=np.arange(20)
print(a[a%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [23]:
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a=np.array(a)
print(a)
a=list(a)
print(a)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
b=np.zeros((10,10))
b[0,:]=1
b[9,:]=1
b[:,0]=1
b[:,9]=1
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [29]:
a=np.array(([1,0]*5+[0,1]*5)*5).reshape(10,10)
print(a)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]
