[View in Colaboratory](https://colab.research.google.com/github/arghac14/Assignment-2/blob/arghac14/arghac14.ipynb)

#Exercise :List

In [50]:
#1
from random import randrange as rg 
dummy_list=[]
for i in range(10):
  dummy_list.append(rg(1,10))
#2
print(dummy_list)
#3
dummy_list.reverse()
print(dummy_list)
#4
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)


[9, 1, 9, 3, 4, 2, 9, 4, 8, 7]
[7, 8, 4, 9, 2, 4, 3, 9, 1, 9]
[7, 8, 4, 9, 2, 4, 3, 9, 1, 9, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [51]:
#5
dummy_dict={i: dummy_list.count(i) for i in dummy_list}
#6
print(dummy_dict)

{7: 1, 8: 1, 4: 3, 9: 3, 2: 2, 3: 1, 1: 2, 200: 1, 16: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


In [52]:
#7
print(sorted(dummy_list))
print(sorted(dummy_list,reverse=True))

[0, 1, 1, 2, 2, 3, 4, 4, 4, 7, 8, 9, 9, 9, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 9, 9, 9, 8, 7, 4, 4, 4, 3, 2, 2, 1, 1, 0]


In [53]:
#8
x=200
dummy_list.remove(200)
print(dummy_list)
x=100
dummy_list.remove(200)

[7, 8, 4, 9, 2, 4, 3, 9, 1, 9, 2, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


ValueError: ignored

In [23]:
#9
x=rg(0,len(dummy_list))
dummy_list.remove(dummy_list[x])
x = len(dummy_list) + 1
dummy_list.remove(dummy_list[x])

ValueError: ignored

In [28]:
#10
dummy_list.clear()
print(dummy_list)

[]


#Exercise :Numpy examples

In [34]:
import numpy as np
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


In [35]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.07727119 0.94246073]
 [0.13679794 0.6883604 ]]


In [37]:
a  ==  np.arange(10)
b  ==  np.linspace(0,10, num=6)
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a[0, 1])   

b[0, 0] = 77   
print(a[0, 1]) 

2
77


In [39]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]  
row_r2 = a[1:2, :] 

print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)  

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [40]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [43]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask])

modified_b = b
modified_b[mask] = -1

print(modified_b)

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [44]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [46]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#Exercise:Numpy exercise


In [47]:
#1
import numpy as np
n=a=np.linspace(-1.3,2.5,num=64)
print(n)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [0]:
#2
n=int(input())
a=np.array([1,2,3])
b=np.resize(a,3*n)
print(b)

In [0]:
#3
arr=np.arange(1,20,2)
print(arr)


In [0]:
#4
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

In [0]:
#5
a = np.arange(10)
print(a.reshape(2,5))

In [0]:
#6
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b=np.array(a)
print(b)
print(a.tolist)


In [0]:
#7
arr=np.ones(shape=(10,10))
arr[1:9,1:9]=0
print(arr)


In [0]:
#8
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)