# Exercise - List

1) Create  any random list and assign it to a variable dummy_list

In [0]:
dummy_list = [1, 9, 8, 5, 6, 20, 5]

2) print dummy_list

In [2]:
dummy_list

[1, 9, 8, 5, 6, 20, 5]

3) Reverse dummy_list and print

In [3]:
dummy_list.reverse()
dummy_list

[5, 20, 6, 5, 8, 9, 1]

4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [4]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list += dummy_list_2
dummy_list

[5, 20, 6, 5, 8, 9, 1, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]

5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values. 

In [0]:
dummy_dict = {}

In [0]:
dummy_list_u = list(set(dummy_list))
for i in dummy_list_u:
  dummy_dict[i] = dummy_list.count(i)

6) print dummy_dict

In [7]:
dummy_dict

{0: 1,
 1: 2,
 2: 1,
 4: 1,
 5: 2,
 6: 1,
 8: 1,
 9: 1,
 9.45: 1,
 12.01: 1,
 12.02: 1,
 16: 1,
 20: 1,
 45.67: 1,
 90: 1,
 200: 1}

7) Sort dummy_list in ascending order as well as descending order and print the changed lists 

In [8]:
dummy_list.sort()
print(dummy_list)
dummy_list.sort(reverse = True)
print(dummy_list)

[0, 1, 1, 2, 4, 5, 5, 6, 8, 9, 9.45, 12.01, 12.02, 16, 20, 45.67, 90, 200]
[200, 90, 45.67, 20, 16, 12.02, 12.01, 9.45, 9, 8, 6, 5, 5, 4, 2, 1, 1, 0]


8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [9]:
x = 200
if(dummy_list.count(x) > 0):
  dummy_list.remove(x)
else:
  raise ValueError("No Such item was found")
dummy_list

[90, 45.67, 20, 16, 12.02, 12.01, 9.45, 9, 8, 6, 5, 5, 4, 2, 1, 1, 0]

9) Remove the item at position x. x is any random integer

In [10]:
import random

x = random.randint(0, len(dummy_list))
dummy_list.pop(x)
print("Removing from ", x)
print(dummy_list)

# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get
x = len(dummy_list) + 2
dummy_list.pop(x)       # Got an Error : IndexError: pop index out of range

Removing from  13
[90, 45.67, 20, 16, 12.02, 12.01, 9.45, 9, 8, 6, 5, 5, 4, 1, 1, 0]


IndexError: ignored

10) Let's clean everything clear the list and then print

In [11]:
dummy_list.clear()
dummy_list

[]

# Numpy Examples

## What is numpy?

#### Python has built-in:

-  containers: lists (costless insertion and append), dictionnaries (fast lookup)
-  high-level number objects: integers, floating point

#### Numpy is:

 - extension package to Python for multidimensional arrays
 - closer to hardware (efficiency)
 - designed for scientific computation (convenience)


#### Import numpy



In [0]:
import numpy as np

### Uncomment Print statement and run each cell to see the output

#### Create numpy arrays


In [13]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


#### Some basic functions for creating arrays. Print all the defined arrays and see the results.

In [14]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.81224677 0.54559982]
 [0.3721418  0.60443163]]


#### Execute and understand :)

In [15]:
a = (a  ==  np.arange(10))
b = (b  ==  np.linspace(0,10, num=6))
print(a)
print(b)


#a  ==  np.arange(10)
#b  ==  np.linspace(0,10, num=6)
#print(a)
#print(b)

False
False


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


#### Array Indexing

In [16]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


#### Slicing

In [17]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Aritmetic operations

In [18]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


#### Using Boolean Mask

In [19]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array


[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [20]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Swapping two columns in a 2d numpy array

In [21]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Swapping two rows in a 2d numpy array

In [22]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])
#print(arr[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [24]:
n = 5
arr = np.resize([1, 2, 3], 3*n)
arr

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3) Create an array of the first 10 odd integers.

In [25]:
odd_arr = np.array(range(10)) * 2 + 1
odd_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4) Find intersection of a and b

In [26]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
intersect = np.intersect1d(a, b)
intersect

array([2, 4])

5) Reshape 1d array a to 2d array of 2X5

In [27]:
a = np.arange(10)
reshape = np.reshape(a, (2, 5))
reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

6) Create a numpy array to list and vice versa

In [28]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np_arr = np.array(a)
print(np_arr)
lst = np_arr.tolist()
print(lst)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [29]:
mat = np.zeros((10, 10))
print(mat)
mat = np.pad(mat, pad_width = 1, mode='constant', constant_values = 1)
print(mat)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [30]:
chk_board = np.zeros((8,8))
#change all the odd arrays with [1, 0, 1, 0...] 
chk_board[1::2, ::2] = 1
#change all the even arrays with [0, 1, 0, 1...]
chk_board[::2, 1::2] = 1

chk_board

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])