[View in Colaboratory](https://colab.research.google.com/github/ArnabG99/Assignment-2/blob/ArnabG99/ArnabG99.ipynb)

# Exercise - List

1) Create  any random list and assign it to a variable dummy_list

In [0]:
import random
dummy_list = [random.randrange(1, 100) for i in range(0, 5)]

2) print dummy_list

In [0]:
print(dummy_list)

[18, 94, 99, 51, 58]


3) Reverse dummy_list and print

In [0]:
dummy_list = dummy_list[ : :-1]
print(dummy_list)

[58, 51, 99, 94, 18]


4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list = dummy_list_2 + dummy_list
print(dummy_list)

[2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02, 58, 51, 99, 94, 18]


*5*) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values. 

In [0]:
dummy_dict = {}
dummy_dict = {x:dummy_list.count(x) for x in dummy_list}

6) print dummy_dict

In [0]:
print(dummy_dict)

{2: 1, 200: 1, 16: 1, 4: 1, 1: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1, 58: 1, 51: 1, 99: 1, 94: 1, 18: 1}


7) Sort dummy_list in ascending order as well as descending order and print the changed lists 

In [0]:
dummy_list.sort(reverse=True)
print(dummy_list)

[200, 99, 94, 90, 58, 51, 45.67, 18, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
dummy_list.remove(x)
# Let's play: try the same with something which is not in the list to get the ValueError

9) Remove the item at position x. x is any random integer

In [0]:
dummy_list.pop(random.randrange(0,len(dummy_list)))
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get

12.01

10) Let's clean everything clear the list and then print

In [0]:
dummy_list = []
print(dummy_list)

[]


# Numpy Examples

## What is numpy?

#### Python has built-in:

-  containers: lists (costless insertion and append), dictionnaries (fast lookup)
-  high-level number objects: integers, floating point

#### Numpy is:

 - extension package to Python for multidimensional arrays
 - closer to hardware (efficiency)
 - designed for scientific computation (convenience)


#### Import numpy



In [0]:
import numpy as np

### Uncomment Print statement and run each cell to see the output

#### Create numpy arrays


In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


#### Some basic functions for creating arrays. Print all the defined arrays and see the results.

In [3]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.99514417 0.36084432]
 [0.58061328 0.22983399]]


#### Execute and understand :)

In [5]:
a  ==  np.arange(10)
b  ==  np.linspace(0,10, num=6)
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


#### Array Indexing

In [8]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


#### Slicing

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Aritmetic operations

In [11]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


#### Using Boolean Mask

In [13]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array


[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [14]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Swapping two columns in a 2d numpy array

In [15]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Swapping two rows in a 2d numpy array

In [18]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

3) Create an array of the first 10 odd integers.

4) Find intersection of a and b

In [0]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10)

6) Create a numpy array to list and vice versa

In [0]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.