[View in Colaboratory](https://colab.research.google.com/github/ASIF8240233397/Assignment-2/blob/ASIF8240233397/ASIF8240233397.ipynb)

In [0]:
import random
dummy_list=[]
for i in range(10):
  dummy_list.append(random.randrange(1,100))

In [2]:
print(dummy_list)

[73, 57, 31, 43, 75, 6, 84, 15, 34, 67]


In [3]:
dummy_list.reverse()
print(dummy_list)

[67, 34, 15, 84, 6, 75, 43, 31, 57, 73]


In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list_1=[12, 4, 5, 6, 7, 8, 9, 10, 45, 98, 14]
dummy_list=dummy_list_1+dummy_list_2
print (dummy_list)


[12, 4, 5, 6, 7, 8, 9, 10, 45, 98, 14, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list_1=[12, 4, 5, 6, 7, 8, 9, 10, 45, 98, 14]
dummy_list=dummy_list_1+dummy_list_2
dummy_list.sort()
print (dummy_list)

[0, 1, 2, 4, 4, 5, 6, 7, 8, 9, 9.45, 10, 12, 12.01, 12.02, 14, 16, 45, 45.67, 90, 98, 200]


In [0]:
import numpy as np
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list_1=[12, 4, 5, 6, 7, 8, 9, 10, 45, 98, 14]
dummy_list=dummy_list_1+dummy_list_2
dummy_list.sort()
dummy_list.pop()
print (dummy_list)

[0, 1, 2, 4, 4, 5, 6, 7, 8, 9, 9.45, 10, 12, 12.01, 12.02, 14, 16, 45, 45.67, 90, 98]


In [0]:
a = np.array([1, 2, 3])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)        
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
(2, 3)
1 2 4


In [0]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print(a)
print(b)
print(c)
print(d)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[0.80700247 0.49397538]
 [0.08392541 0.02261966]]


In [0]:
a  =  np.arange(10)
b  =  np.linspace(0,10, num=6)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a[0, 1])  

b[0, 0] = 77   
print(a[0, 1])

2
77


In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]   
row_r2 = a[1:2, :] 
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape) 

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [0]:
x = np.array([[1,2],[3,4]])

print(np.sum(x)) 
print(np.sum(x, axis=0)) 
print(np.sum(x, axis=1)) 

10
[4 6]
[3 7]


In [0]:
b = np.arange(10)

print(b)

mask = b%2!=0 
print(mask)
print(b[mask])


[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [0]:
modified_b = b
modified_b[mask] = -1
print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [0]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [0]:
a = np.arange(9).reshape(3,3)
print(a)
print([[1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1, 0, 2]]


In [0]:
array1=[]
diff=(2.5-1.3)/64
for i in range(64):
    array1.append(1.3+(i*diff))
print(array1)
print(len(array1))


[1.3, 1.31875, 1.3375000000000001, 1.35625, 1.375, 1.39375, 1.4125, 1.4312500000000001, 1.45, 1.46875, 1.4875, 1.50625, 1.525, 1.54375, 1.5625, 1.58125, 1.6, 1.61875, 1.6375, 1.65625, 1.675, 1.69375, 1.7125, 1.73125, 1.75, 1.76875, 1.7875, 1.80625, 1.8250000000000002, 1.84375, 1.8625, 1.88125, 1.9, 1.9187500000000002, 1.9375, 1.95625, 1.975, 1.99375, 2.0125, 2.03125, 2.05, 2.06875, 2.0875, 2.10625, 2.125, 2.14375, 2.1625, 2.18125, 2.2, 2.21875, 2.2375, 2.25625, 2.275, 2.29375, 2.3125, 2.33125, 2.35, 2.36875, 2.3875, 2.40625, 2.425, 2.44375, 2.4625, 2.48125]
64


In [0]:
import numpy as np
n=input("Enter a no.: ")
array1=np.arange(1,3*int(n)+1)
print (array1)
for j in range(len(array1)):
    
    c=array1[0]

    for i in range(len(array1)-1):
    
        array1[i]=array1[i+1]

    array1[len(array1)-1]=c
    print (array1)

Enter a no.: 2
[1 2 3 4 5 6]
[2 3 4 5 6 1]
[3 4 5 6 1 2]
[4 5 6 1 2 3]
[5 6 1 2 3 4]
[6 1 2 3 4 5]
[1 2 3 4 5 6]


In [0]:
lower=int(input("Enter the lower limit for the range:"))
upper=int(input("Enter the upper limit for the range:"))
for i in range(lower,upper+1):
    if(i%2!=0):
        print(i)

Enter the lower limit for the range:1
Enter the upper limit for the range:21
1
3
5
7
9
11
13
15
17
19
21


In [0]:
set1 = {2, 4, 5, 6}  
set2 = {4, 6, 7, 8}   
print("set1 intersection set2 : ", set1.intersection(set2)) 
 

set1 intersection set2 :  {4, 6}


In [0]:
from numpy import array
data = array([[11, 22, 33],
		[44, 55, 66],
		[77, 88, 99]])
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [0]:
import numpy as np
import numpy as np
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [0]:
import numpy as np
x = np.zeros((10,10))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=1)
print(x)

Original array:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0 on the border and 1 inside in the array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [0]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
