[View in Colaboratory](https://colab.research.google.com/github/Anb91/Assignment-2/blob/Anb91/asignment1.ipynb)

In [0]:
import random
dummy_list=[]
for i in range(10):
  dummy_list.append(random.randrange(10))


In [3]:
print(dummy_list)

[5, 6, 7, 3, 0, 3, 9, 7, 5, 1]


In [4]:
dummy_list.reverse()
print(dummy_list)

[1, 5, 7, 9, 3, 0, 3, 7, 6, 5]


In [5]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)

[1, 5, 7, 9, 3, 0, 3, 7, 6, 5, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_dict={i:dummy_list.count(i) for i in dummy_list}


In [7]:
print(dummy_dict)

{1: 2, 5: 2, 7: 2, 9: 1, 3: 2, 0: 2, 6: 1, 2: 1, 200: 1, 16: 1, 4: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


In [8]:
print(sorted(dummy_list))
print(sorted(dummy_list,reverse=True))

[0, 0, 1, 1, 2, 3, 3, 4, 5, 5, 6, 7, 7, 9, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 9, 7, 7, 6, 5, 5, 4, 3, 3, 2, 1, 1, 0, 0]


In [0]:
dummy_list.remove(200)


In [10]:
dummy_list.remove(11)

ValueError: ignored

In [11]:
dummy_list.pop(7)

7

In [12]:
dummy_list.pop(500)

IndexError: ignored

In [0]:
dummy_list.clear()

In [14]:
print(dummy_list)

[]


In [0]:
import numpy as np

In [16]:
x = np.array([1,2,3])
y = np.resize(x, 13)
y

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1])

In [17]:
x=[]
for i in range(1,20,2):
  x.append(i)
x=np.array(x)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a=set(a)
b=set(b)
c=a.intersection(b)
print(c)

{2, 4}


In [19]:
a= np.arange(10)
b= np.reshape(a,(2,5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
array = np.array(a)
print(array)
list=array.tolist()
list

[1 2 3 4 5 6 7 8 9]


[1, 2, 3, 4, 5, 6, 7, 8, 9]