[View in Colaboratory](https://colab.research.google.com/github/devjeetroy98/Assignment-2/blob/devjeetroy98/assignment2_MLCC.ipynb)

In [0]:
dummy_list=[10,20,16,60]


In [75]:
print(dummy_list)

[10, 20, 16, 60]


In [76]:
print(dummy_list[::-1])

[60, 16, 20, 10]


In [77]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list=dummy_list_2 + dummy_list
print(dummy_list)

[2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02, 10, 20, 16, 60]


In [0]:
dummy_dict={}
for i in dummy_list:
  if i in dummy_dict:
    dummy_dict[i]+=1
  else:
    dummy_dict[i]=1
    
  

In [79]:
print(dummy_dict)

{2: 1, 200: 1, 16: 2, 4: 1, 1: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1, 10: 1, 20: 1, 60: 1}


In [59]:
print(sorted(dummy_list))
print(sorted(dummy_list,reverse=True))

[0, 1, 2, 4, 9.45, 10, 12.01, 12.02, 16, 16, 20, 45.67, 60, 90, 200]
[200, 90, 60, 45.67, 20, 16, 16, 12.02, 12.01, 10, 9.45, 4, 2, 1, 0]


In [80]:
x=200
dummy_list.remove(200)
print(dummy_list)
x=100
dummy_list.remove(200)
print(dummy_list)

[2, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02, 10, 20, 16, 60]


ValueError: ignored

In [81]:
from random import randrange as rg
x=rg(0,len(dummy_list))
dummy_list.remove(dummy_list[x])
x=len(dummy_list)+1
dummy_list.remove(dummy_list[x])

IndexError: ignored

In [82]:
dummy_list.clear()
print(dummy_list)

[]


**Numpy** **Examples**

In [83]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9])
print(array)
print(type(array))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [84]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.98137658 0.70825382]
 [0.53037546 0.83010548]]


In [85]:
a  ==  np.arange(10)
b  ==  np.linspace(0,10, num=6)
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


In [86]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [87]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [88]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [89]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [90]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [91]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [94]:
arr=[]
a = np.arange(9).reshape(3,3)
print(a)

print(arr[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


TypeError: ignored

**Numpy** **Exersise**s

In [116]:
import numpy as np
n=np.linspace(-1.3,2.5,64)
print(n)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [117]:
n=int(input())
a=np.array([1,2,3])
b=np.resize(a,3*n);
print(b)

1
[1 2 3]


In [118]:
arr=np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [119]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b)) #1d for one dim array

[2 4]


In [120]:
a = np.arange(10)
print(*a.reshape(2,5))

[0 1 2 3 4] [5 6 7 8 9]


In [121]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr=np.array(a)
print(arr)
print(a.tolist)

[1 2 3 4 5 6 7 8 9]


AttributeError: ignored

In [125]:
import numpy as np
x=np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [126]:
import numpy as np
x=np.ones((3,3))
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
