[View in Colaboratory](https://colab.research.google.com/github/Anubhab-Bob/Assignment-2/blob/Anubhab-Bob/Assignment_2.ipynb)

In [0]:
dummy_list=[1, 2, 3, 4, 5, 3]

In [43]:
print(dummy_list)

[1, 2, 3, 4, 5, 3]


In [44]:
dummy_list.reverse()
print(dummy_list)
#for o in reversed(dummy_list):
#   print(o)

[3, 5, 4, 3, 2, 1]


In [45]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)

[3, 5, 4, 3, 2, 1, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_dict={}

In [0]:
i=0
while i!= len(dummy_list):
  if dummy_list[i] not in dummy_dict:
    dummy_dict[dummy_list[i]]=1
  else:
    for key,value in dummy_dict.items():
      if key == dummy_list[i]:
        dummy_dict[key] = value + 1
        break
      #print("Key: "    + str(key))
      #print ("Value: " + str(value))
  i = i + 1
  #print(i)

In [48]:
for key, value in dummy_dict.items():
    print("Key: "    + str(key))
    print ("Value: " + str(value))
    print('\n')

Key: 3
Value: 2


Key: 5
Value: 1


Key: 4
Value: 2


Key: 2
Value: 2


Key: 1
Value: 2


Key: 200
Value: 1


Key: 16
Value: 1


Key: 0
Value: 1


Key: 9.45
Value: 1


Key: 45.67
Value: 1


Key: 90
Value: 1


Key: 12.01
Value: 1


Key: 12.02
Value: 1




In [49]:
'''for key in sorted(dummy_dict.keys()):
    print ("Key :" + str(key) + '\t\t\t' + "Value :" + str(dummy_dict[key]))

print("\n\n")
for key in sorted(dummy_dict.keys(), reverse=True):
    print ("Key :" + str(key) + '\t\t\t' + "Value :" + str(dummy_dict[key]))'''

dummy_list.sort()
print(dummy_list)
print('\n')
dummy_list.sort(reverse=True)
print(dummy_list)
#print(sorted(dummy_list, reversed=True))

[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]


[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 5, 4, 4, 3, 3, 2, 2, 1, 1, 0]


In [50]:
x=200
dummy_list.remove(x)
print(dummy_list)

[90, 45.67, 16, 12.02, 12.01, 9.45, 5, 4, 4, 3, 3, 2, 2, 1, 1, 0]


In [51]:
del dummy_list[5]
print (dummy_list)

[90, 45.67, 16, 12.02, 12.01, 5, 4, 4, 3, 3, 2, 2, 1, 1, 0]


In [52]:
dummy_list.clear()
print(dummy_list)

[]


# Now the Numpy part

In [0]:
import numpy as np

In [54]:
b  =  np.linspace(1.3,2.5, num=64)
print (b)

[1.3        1.31904762 1.33809524 1.35714286 1.37619048 1.3952381
 1.41428571 1.43333333 1.45238095 1.47142857 1.49047619 1.50952381
 1.52857143 1.54761905 1.56666667 1.58571429 1.6047619  1.62380952
 1.64285714 1.66190476 1.68095238 1.7        1.71904762 1.73809524
 1.75714286 1.77619048 1.7952381  1.81428571 1.83333333 1.85238095
 1.87142857 1.89047619 1.90952381 1.92857143 1.94761905 1.96666667
 1.98571429 2.0047619  2.02380952 2.04285714 2.06190476 2.08095238
 2.1        2.11904762 2.13809524 2.15714286 2.17619048 2.1952381
 2.21428571 2.23333333 2.25238095 2.27142857 2.29047619 2.30952381
 2.32857143 2.34761905 2.36666667 2.38571429 2.4047619  2.42380952
 2.44285714 2.46190476 2.48095238 2.5       ]


In [55]:
n = int(input())
x = np.array([1, 2, 3])
y = np.tile(x,(3*n))
print (y)

3
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [56]:
b = np.arange(20)

#print(b)

mask = b%2!=0 #perform computations on the list 

#print(mask)

print(b[mask]) #applying the mask on the numpy array

[ 1  3  5  7  9 11 13 15 17 19]


In [57]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [58]:
a = np.arange(10)
print (a)
print('\n')
a.shape = a.size//-1, 5
print(a)

[0 1 2 3 4 5 6 7 8 9]


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [59]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.array(a).tolist()
print(a)
print('\n')
np.asarray(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]




array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
d = np.ones((5,5))
d[1:-1,1:-1] = 0
print(d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
