In [1]:
#random list
random_list=[1,2,3,4,5]
dummy_list=[]
i=0
while i<len(random_list):
  dummy_list.append(random_list[i])
  i+=1
print(dummy_list)

[1, 2, 3, 4, 5]


In [2]:
dummy_list.reverse()
print(dummy_list)

[5, 4, 3, 2, 1]


In [3]:
dummy_list.reverse()
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)

[1, 2, 3, 4, 5, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [4]:
#counter is the dictionary that stores key value pairs of elementsand frequnecy
import collections
dummy_dict=collections.Counter(dummy_list)
print(dummy_dict)


Counter({1: 2, 2: 2, 4: 2, 3: 1, 5: 1, 200: 1, 16: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1})


In [5]:
#ascending order
print(sorted(dummy_list))
#descending order
print(sorted(dummy_list,reverse=True))

[0, 1, 1, 2, 2, 3, 4, 4, 5, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 5, 4, 4, 3, 2, 2, 1, 1, 0]


In [6]:
'''X=input("Enter value to remove from list")
i=0
while i<len(dummy_list):
  if dummy_list[i]==X:
    del dummy_list[i]
  i+=1
'''  

'X=input("Enter value to remove from list")\ni=0\nwhile i<len(dummy_list):\n  if dummy_list[i]==X:\n    del dummy_list[i]\n  i+=1\n'

In [7]:
'''def remove_value_from_list(list1,val):
  return[value for value in list1 if value!=val]
X=input()
dummy_list=remove_value_from_list(dummy_list,X)
print(dummy_list)
'''

'def remove_value_from_list(list1,val):\n  return[value for value in list1 if value!=val]\nX=input()\ndummy_list=remove_value_from_list(dummy_list,X)\nprint(dummy_list)\n'

In [0]:
x=input()
dummy_list[:]=(value for value in dummy_list if value!=x)
#dummy_list.remove(x)
print(dummy_list)

In [0]:
X=input()
a=int(X)
del dummy_list[a]
print(dummy_list)

In [0]:
dummy_list.clear()
print(dummy_list)


Assignment 2 NUMPY Exercise


In [0]:
import numpy as np

In [10]:
#cyclic pattern

X=np.array([1,2,3])
Y=np.resize(X,13)
print(Y)

[1 2 3 1 2 3 1 2 3 1 2 3 1]


In [11]:
#first 10 odd integers
odd=np.array([i for i in range(1,20) if i%2!=0])
print(odd)

[ 1  3  5  7  9 11 13 15 17 19]


In [12]:
#intersection of a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)
print(c)

[2 4]


In [13]:
#Reshape
print(np.arange(10).reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
#list to array &vice-versa
a = np.arange(0,10)
a.tolist()
print(a)
b=np.asarray(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
#10*10  array with zeroes in border
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
#checker board
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
