[View in Colaboratory](https://colab.research.google.com/github/rupamcyrax799/Assignment-2/blob/rupamcyrax799/Assignment%202%20(Numpy%20Exercise).ipynb)

 ***NUMPY EXERCISE***





In [2]:
import numpy as np 
a=np.linspace(-1.3,2.5,64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [3]:
#Generating cyclic array of length 3n
a=np.array([1,2,3])
print (a)
n=input("Enter the array length : ")
b=np.resize(a,(3*int(n)))
print (b)

[1 2 3]
Enter the array length : 4
[1 2 3 1 2 3 1 2 3 1 2 3]


In [4]:
#Generating an array of the first 10 odd numbers
a= np.arange(1,20,2)
print("Set of first 10 odd numbers: ")
print(a)

Set of first 10 odd numbers: 
[ 1  3  5  7  9 11 13 15 17 19]


In [5]:
#Finding the intersection between two arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
op=np.intersect1d(a,b)
print(op)

[2 4]


In [6]:
#Reshaping an Array
a = np.arange(10)
op= np.reshape(a,(-1,5))
print(op)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
#Conversion of list to a Numpy Array
a = [0,1, 2, 3, 4, 5, 6, 7, 8, 9]
op=np.array(a)
print("Numpy ARRAY: ")
print(op)
#Conversion of a Numpy array into a List
a= np.array([0,1,2,3,4,5,6,7,8,9])
op= a.tolist()
print("List: ")
print(op)

Numpy ARRAY: 
[0 1 2 3 4 5 6 7 8 9]
List: 
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
#Generating an array With the border elements As 1's and the inner elements as 0's
a=np.zeros(shape=(10,10))
a[:,0]=1
a[0,:]=1
a[:,9]=1
a[9,:]=1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
#Printing an array with a CHECKERBOX PATTERN
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
