# **Exercise - List**

In [0]:
dummy_list = [1,7,9,2]

In [0]:
print(dummy_list)

[1, 7, 9, 2]


In [0]:
dummy_list.reverse()
print(dummy_list)

[2, 9, 7, 1]


In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)


[2, 9, 7, 1, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_dict= {x:dummy_list.count(x) for x in dummy_list}

In [0]:
print(dummy_dict)

{2: 2, 9: 1, 7: 1, 1: 2, 200: 1, 16: 1, 4: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


In [0]:
dummy_list.sort()
print(dummy_list)

[0, 1, 1, 2, 2, 4, 7, 9, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]


In [0]:
dummy_list.sort(reverse=True)
print(dummy_list)

[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 9, 7, 4, 2, 2, 1, 1, 0]


In [0]:
x=200 #Lets PLay
dummy_list.remove(x)

In [0]:
x=3
del dummy_list[x]

In [0]:
dummy_list.clear()

In [0]:
print(dummy_list)

[]


# Numpy Examples


In [0]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


In [5]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.83493885 0.60763004]
 [0.05343786 0.16618978]]


In [7]:
a = np.arange(10)
b = np.linspace(0,10, num=6)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


In [8]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]

print(a[0, 1])   

b[0, 0] = 77     
print(a[0, 1])   

2
77


In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    
row_r2 = a[1:2, :]  

print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape) 

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [10]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  
print(np.sum(x, axis=0))  
print(np.sum(x, axis=1))  

10
[4 6]
[3 7]


In [11]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array


[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [12]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [15]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


# Numpy Excercises

In [0]:
import numpy as np
a = np.linspace(-1.3,2.5,64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [0]:
n=3
a = np.array([1,2,3])
b = np.resize(a,3*n)
print(b)

[1 2 3 1 2 3 1 2 3]


In [0]:
a= np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [0]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
n = np.intersect1d(a,b)
print(n)

[2 4]


In [0]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [0]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(a)
print("Array : " + str(a))
a.tolist()
print("List : "+ str(a))

Array : [1 2 3 4 5 6 7 8 9]
List : [1 2 3 4 5 6 7 8 9]


In [0]:
a = np.zeros(shape=(10,10))
a[:,0]=1
a[0,:]=1
a[:,9]=1
a[9,:]=1
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [0]:
a= np.ones(shape=(8,8))
a[1::2,::2]=0
a[::2,1::2]=0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
