# **Exercise - List**

1) Create any random list and assign it to a variable dummy_list

In [0]:
dummy_list = [24, 6, 1997, 7.53] 

2) print dummy_list

In [2]:
print(dummy_list)

[24, 6, 1997, 7.53]


3) Reverse dummy_list and print

In [3]:
dummy_list.reverse()
print(dummy_list)

[7.53, 1997, 6, 24]


4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [4]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)


[7.53, 1997, 6, 24, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values.

In [0]:
dummy_dict = {}
for i in range(len(dummy_list)):
  x = dummy_list.count(dummy_list[i])
  dummy_dict.update({dummy_list[i]:x})

6) print dummy_dict

In [6]:
print(dummy_dict)

{7.53: 1, 1997: 1, 6: 1, 24: 1, 2: 1, 200: 1, 16: 1, 4: 1, 1: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


7) Sort dummy_list in ascending order as well as descending order and print the changed lists


In [7]:
dummy_list.sort()
print(dummy_list)
dummy_list.sort(reverse=True)
print(dummy_list)

[0, 1, 2, 4, 6, 7.53, 9.45, 12.01, 12.02, 16, 24, 45.67, 90, 200, 1997]
[1997, 200, 90, 45.67, 24, 16, 12.02, 12.01, 9.45, 7.53, 6, 4, 2, 1, 0]


8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
if x in dummy_list:
  dummy_list.remove(x)
else:
  raise ValueError("there is no such item")

9) Remove the item at position x. x is any random integer

In [9]:
from random import randrange
x = randrange(0,len(dummy_list))
dummy_list.pop(x)

7.53

10) Let's clean everything clear the list and then print

In [10]:
dummy_list.clear()
print(dummy_list)

[]


# **Numpy Examples**

**Import numpy**

In [0]:
import numpy as np

**Create numpy arrays**

In [12]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


**Some basic functions for creating arrays**

In [13]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.85464756 0.49703993]
 [0.1809922  0.49154666]]


**Execute and understand**

In [14]:
a = np.arange(10)
b = np.linspace(0,10, num=6)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


**Array Indexing**

In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


**Slicing**

In [16]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Aritmetic operations**

In [17]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


**Using Boolean Mask**

In [18]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [19]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Swapping two columns in a 2d numpy array**

In [20]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


**Swapping two rows in a 2d numpy array**

In [21]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


# **Numpy Exercises**

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [22]:
import numpy as np
a = np.linspace(-1.3,2.5,64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [0]:
n = 15
a = np.array([1,2,3])
a = np.resize(a,n)

3) Create an array of the first 10 odd integers.

In [0]:
a = np.arange(1,20,2)

4) Find intersection of a and b

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

5) Reshape 1d array a to 2d array of 2X5

In [26]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [0]:
a = np.array([[1,2],[3,4]])
al = a.tolist()

bl = [[1,2],[3,4]]
b = np.asarray(bl)

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [28]:
a = np.zeros(shape = (10,10))
a[0,:] = 1
a[9,:] = 1
a[:,0] = 1
a[:,9] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.


In [0]:
a = np.zeros((8,8), dtype = int)
# starts from 1st row, skips 1 row, skips 1 column
a[1::2,::2] = 1
a[::2,1::2] = 1 