[View in Colaboratory](https://colab.research.google.com/github/Debjit08/Assignment-2/blob/Debjit08/Debjit08_Numpy_Examples_1.ipynb)

# Numpy Examples

## What is numpy?

#### Python has built-in:

-  containers: lists (costless insertion and append), dictionnaries (fast lookup)
-  high-level number objects: integers, floating point

#### Numpy is:

 - extension package to Python for multidimensional arrays
 - closer to hardware (efficiency)
 - designed for scientific computation (convenience)


#### Import numpy



In [0]:
import numpy as np

### Uncomment Print statement and run each cell to see the output

#### Create numpy arrays


In [0]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


#### Some basic functions for creating arrays. Print all the defined arrays and see the results.

In [0]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.98338295 0.76776373]
 [0.72112205 0.72726464]]


#### Execute and understand :)

In [0]:
a  =  np.arange(10)
b  =  np.linspace(-1.2,2.5, num=64)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[-1.2        -1.14126984 -1.08253968 -1.02380952 -0.96507937 -0.90634921
 -0.84761905 -0.78888889 -0.73015873 -0.67142857 -0.61269841 -0.55396825
 -0.4952381  -0.43650794 -0.37777778 -0.31904762 -0.26031746 -0.2015873
 -0.14285714 -0.08412698 -0.02539683  0.03333333  0.09206349  0.15079365
  0.20952381  0.26825397  0.32698413  0.38571429  0.44444444  0.5031746
  0.56190476  0.62063492  0.67936508  0.73809524  0.7968254   0.85555556
  0.91428571  0.97301587  1.03174603  1.09047619  1.14920635  1.20793651
  1.26666667  1.32539683  1.38412698  1.44285714  1.5015873   1.56031746
  1.61904762  1.67777778  1.73650794  1.7952381   1.85396825  1.91269841
  1.97142857  2.03015873  2.08888889  2.14761905  2.20634921  2.26507937
  2.32380952  2.38253968  2.44126984  2.5       ]


#### Array Indexing

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


#### Slicing

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Aritmetic operations

In [0]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


#### Using Boolean Mask

In [0]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 
print(b[mask]) #applying the mask on the numpy array


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [0]:
modified_b = b[mask]

print(modified_b)

[1 3 5 7 9]


#### Swapping two columns in a 2d numpy array

In [0]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Swapping two rows in a 2d numpy array

In [0]:
a = np.arange(9).reshape(3,3)
print(a)

a=a[[1,0,2], :]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
