In [1]:
#numpy exercises
import numpy as np
a1 = np.array([1, 2, 3])
b1 = np.array([1, 3, 5,7,9,11,13,15,17,19])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.array([i for i in a if i in b])
v,counts_elements = np.unique(c,return_counts=True)
print(v)
a = np.arange(10).reshape(2,5)
print (a)
a2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a3=np.zeros(shape=(10,10))
a3_mod=a3
for j in range(len(a3)-1,-1,-1):
    for s in range(len(a3[0])-1,-1,-1):
        if j==0 or j==9:
            a3_mod[s][j]=1
        if s==0 or s==9:
            a3_mod[s][j]=1

print (a3)
print(" ")

a8=a3[1:8,1:8]
for row in range(len(a8)-1,-1,-1):
    for col in range(len(a8[0])-1,-1,-1):
        if (row+col)%2==0:
            a8[row][col]=1
print(a8)

[2 4]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 
[[1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1.]]


In [3]:
#numpy_examples assignment
import numpy as np
a = np.array([1, 2, 3]) 
print(a)
print(type(a))

b = np.array([[1,2,3],[4,5,6]]) 
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])
a1 = np.zeros(shape=(2,2))
b1 = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))
print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
a  =  np.arange(10)
b  =  np.linspace(0,10, num=6)
print(a)
print(b)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


b = a[0:2, 1:3]

print(a[0, 1]) 

b[0, 0] = 77   
print(a[0, 1])
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    
row_r2 = a[1:2, :]  

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

x = np.array([[1,2],[3,4]])

print(np.sum(x)) 
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
x = np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
b = np.arange(10)
print(b)

mask = b%2!=0  
print(mask)
print(b[mask])

modified_b = b
modified_b[mask] = -1

print(modified_b)
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])
a = np.arange(9).reshape(3,3)
print(a)
print(a[[1,0,2], :])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4
a [1 2 3]
b [[1 2 3]
 [4 5 6]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.61177267 0.86052321]
 [0.83381321 0.92172796]]
[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]
2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
10
[4 6]
[3 7]
10
[4 6]
[3 7]
[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [2]:
#list assignment
dummy_list=[1,2,3,4]
print (dummy_list)
dummy_list.reverse()
print (dummy_list)
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
for i in range(len(dummy_list_2)-1,-1,-1):
    dummy_list.append(dummy_list_2[i])
print (dummy_list)
dummy_dict={1:2,2:3,3:4,4:5}
print(dummy_dict)
dummy_list.sort()
dummy_list.sort(reverse=True)
print (dummy_list)
x = 200
dummy_list.remove(x)
x=13
dummy_list.remove(x)
dummy_list.clear()
print(dummy_list)


[1, 2, 3, 4]
[4, 3, 2, 1]
[4, 3, 2, 1, 12.02, 12.01, 90, 45.67, 9.45, 0, 1, 4, 16, 200, 2]
{1: 2, 2: 3, 3: 4, 4: 5}
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 4, 4, 3, 2, 2, 1, 1, 0]


ValueError: ignored