# Exercise - List

1) Create  any random list and assign it to a variable dummy_list

In [0]:
dummy_list = [1,2,3,4]

2) print dummy_list

In [0]:
print(dummy_list)

[1, 2, 3, 4]


3) Reverse dummy_list and print

In [0]:
dummy_list.reverse()

4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)

[4, 3, 2, 1, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values. 

In [0]:
dummy_dict = {}
for x in dummy_list:
  if x in dummy_dict:
    dummy_dict[x] +=1
  else:
    dummy_dict[x] = 1

6) print dummy_dict

In [0]:
print(dummy_dict)

{4: 2, 3: 1, 2: 2, 1: 2, 200: 1, 16: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


7) Sort dummy_list in ascending order as well as descending order and print the changed lists 

In [0]:
dummy_list.sort()
print(dummy_list)
dummy_list.sort(reverse = True)
print(dummy_list)

[0, 1, 1, 2, 2, 3, 4, 4, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 4, 4, 3, 2, 2, 1, 1, 0]


8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
dummy_list.remove(x)
x = 201
# Let's play: try the same with something which is not in the list to get the ValueError
dummy_list.remove(x)

ValueError: ignored

9) Remove the item at position x. x is any random integer

In [0]:
x = 1
del dummy_list[x]

x = len(dummy_list) + 2
del dummy_list[x]
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get

IndexError: ignored

10) Let's clean everything clear the list and then print

In [0]:
del dummy_list[:]
print(dummy_list)

[]


# Numpy Examples

## What is numpy?

#### Python has built-in:

-  containers: lists (costless insertion and append), dictionnaries (fast lookup)
-  high-level number objects: integers, floating point

#### Numpy is:

 - extension package to Python for multidimensional arrays
 - closer to hardware (efficiency)
 - designed for scientific computation (convenience)


#### Import numpy



In [0]:
import numpy as np

### Uncomment Print statement and run each cell to see the output

#### Create numpy arrays


In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


#### Some basic functions for creating arrays. Print all the defined arrays and see the results.

In [4]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.2814501  0.00107122]
 [0.45219171 0.94535936]]


#### Execute and understand :)

In [5]:
a  ==  np.arange(10)
b  ==  np.linspace(0,10, num=6)
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


#### Array Indexing

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


#### Slicing

In [7]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Aritmetic operations

In [8]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


#### Using Boolean Mask

In [9]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array


[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [10]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Swapping two columns in a 2d numpy array

In [11]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


#### Swapping two rows in a 2d numpy array

In [13]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [14]:
import numpy as np #import numpy
a = np.linspace(-1.3, 2.5, num=64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [15]:
n = 10
a = [1, 2, 3]
a_gen = np.resize(a, 3*n)
print(a_gen)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [17]:
a = np.arange(1, 20, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [18]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
intersect = np.intersect1d(a, b)
print(intersect)

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [21]:
a = np.arange(10)
reshaped = np.reshape(a, (2, 5))
print(reshaped)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [22]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
numpy_arr = np.array(a)
print(numpy_arr)

list_arr = numpy_arr.tolist()
print(list_arr)


[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [27]:
a = np.zeros((10,10))
a[[0,9],:] = 1
a[:,[0,9]] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [36]:
a = np.zeros((8, 8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
