In [0]:
dummy_list = [1,2,3,4,5,6]

In [0]:
print(dummy_list)

In [0]:
print(dummy_list.reverse())

In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list = dummy_list + dummy_list2
print(dummy_list)

In [0]:
dummy_dict = {}
for i in dummy_list :
  dummy_dict[i] = dummy_list.count(i)
  


In [0]:
print(dummy_list)

In [0]:
print(dummy_list.sort)
print(dummy_list.sort(reverse=True))


In [0]:
x= 200
dummy_list.remove(x)


In [0]:
pos = len(dummy_list) + 1
del dummy_list[pos]


In [0]:
dummy_list.clear()


CODE FOR ASSIGNMENT 2

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3]) #rank of Array = 1
print(a)
print(type(a))

b = np.array([[1,2,3],[4,5,6]]) #create a rank 2 array
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

In [0]:
a = np.zeros(shape=(2,2))
b = np.ones(shape=(3,3))
c = np.eye(3)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

In [0]:
a  ==  np.arange(10)
b  ==  np.linspace(0,10, num=6)
print(a)
print(b)

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a[0, 1])  

b[0, 0] = 77    
print(a[0, 1])  

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]    
row_r2 = a[1:2, :] 
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)

In [0]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)

In [0]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))  
print(np.sum(x, axis=0)) 
print(np.sum(x, axis=1))  

In [0]:
b = np.arange(10)

print(b)

mask = b%2!=0  

print(mask)

print(b[mask]) 


In [0]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

In [0]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

In [0]:
a = np.arange(9).reshape(3,3)
print(a)

print(arr[[1,0,2], :])

CODE ASSIGNMENT 3

In [0]:
import numpy as np 

In [5]:
np.random.uniform(-1.3,2.5,64)

array([ 1.66874192, -0.03366204, -0.47805977,  1.67995305,  1.54163532,
       -0.51235517, -0.54326003,  1.67506967,  0.53346412, -0.34954369,
       -0.62971028,  1.62369023, -0.62588714,  2.48889865,  0.42213678,
        1.27359279, -0.49951592,  1.13097161, -0.59410103, -0.76514773,
        0.99471635, -0.29533933,  1.77896742,  0.90485033,  0.09424771,
        2.07409343,  0.3224667 ,  1.44506873,  0.58749607,  1.95000655,
       -0.20318663,  2.21271676,  2.32491257,  0.07958493,  0.13428842,
        2.05718046, -1.28337008,  1.26805792,  1.92311082,  1.1340207 ,
        1.10523529,  0.34401946, -0.66405786, -1.09433193,  0.12800502,
        2.26766296,  0.8291561 ,  1.08467276, -0.0429127 ,  0.63566009,
       -1.11258385,  0.74501757,  2.1681577 , -0.74749088,  0.85382273,
        1.00538889,  2.49278987, -0.75310541,  2.2836877 , -0.08756215,
       -0.72598515, -0.58122979, -0.32571844,  1.17036431])

In [6]:
z = np.array([1,2,3])
print(np.resize(z,18))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [7]:
b = np.arange(20)
mask = b%2!=0
b[mask]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.union1d(a,b))
print(np.intersect1d(a,b))

[ 1  2  3  4  5  6  7  8  9 10]
[2 4]


In [9]:
a =np.arange(10).reshape(2,5)
print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
a =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(type(a))
a = list(a)
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [11]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
