In [0]:
dummy_list = [ 5, 4, 3, 2, 1, 7, 6, -1, 0]

In [25]:
print(dummy_list)

[5, 4, 3, 2, 1, 7, 6, -1, 0]


In [5]:
print(dummy_list[::-1])

[0, -1, 6, 7, 1, 2, 3, 4, 5]


In [26]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list = dummy_list + dummy_list_2
print(dummy_list)

[5, 4, 3, 2, 1, 7, 6, -1, 0, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [29]:
dummy_dict = {}
for ele in dummy_list:
  if ele not in dummy_dict.keys():
    dummy_dict[ele] = 1
  else:
    dummy_dict[ele] += 1
print(dummy_dict)

{5: 1, 4: 2, 3: 1, 2: 2, 1: 2, 7: 1, 6: 1, -1: 1, 0: 2, 200: 1, 16: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


In [33]:
dummy_list.sort()
print(dummy_list)
dummy_list.sort(reverse=True)
print(dummy_list)

[-1, 0, 0, 1, 1, 2, 2, 3, 4, 4, 5, 6, 7, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0, -1]


In [37]:
x = 200
dummy_list.remove(x)

[90, 45.67, 16, 12.02, 12.01, 9.45, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0, -1]


ValueError: ignored

In [41]:
x = 5
del dummy_list[x]

[90, 45.67, 16, 12.02, 12.01, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0, -1]


In [42]:
dummy_list = []
print(dummy_list)

[]


In [48]:
import numpy as np

# Create a rank 1 array
a = np.array([1, 2, 3])
print(a)

#print type of a
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [50]:
# Create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])

print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [54]:
#Some basic functions for creating arrays

a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a',a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.64933266 0.10821625]
 [0.71282106 0.97982041]]


In [57]:
a  =  np.arange(10)
b  =  np.linspace(0,10, num=6)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


In [58]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

#slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2)
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [59]:
print(a[0, 1])

2


In [61]:
b[0, 0] = 77
print(a[0, 1])


77


In [62]:
# Array Indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Rank 1 view of the second row of a
row_r1 = a[1, :]   

# Rank 2 view of the second row of a
row_r2 = a[1:2, :]  

print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape) 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [63]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [64]:
# Aritmetic operations
x = np.array([[1,2],[3,4]])

# Compute sum of all elements
print(np.sum(x)) 

# Compute sum of each column
print(np.sum(x, axis=0))  

# Compute sum of each row
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [65]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
#perform computations on the list 
mask = b%2!=0
print(mask)

#applying the mask on the numpy array
print(b[mask])

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [67]:
# Using Boolean Mask
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [68]:

a = np.arange(9).reshape(3,3)
print(a)

# Swapping two columns in a 2d numpy array
print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [71]:
a = np.arange(9).reshape(3,3)
print(a)

# Swapping two rows in a 2d numpy array
print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [101]:
import numpy as np

#Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

a = np.linspace(-1.3,2.5, num = 64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [80]:
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

a = np.resize(np.array([1,2,3]), 9)
print(a)


[1 2 3 1 2 3 1 2 3]


In [103]:
# Create an array of the first 10 odd integers

a = np.arange(1, 20, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [81]:
#Find intersection of a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

ans = np.intersect1d(a, b)
print(ans)


[2 4]


In [83]:
#Reshape 1d array a to 2d array of 2X5

a = np.arange(10)
b = a.reshape(2,5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [85]:
#Create a numpy array to list and vice versa

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
numpy_array = np.array(a)
print(numpy_array)

_list_ = list(numpy_array)
print(_list_)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [97]:
#Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

a = np.ones(shape = (10, 10))
a[1:9, 1:9] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [106]:
#Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1

print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
