In [0]:
dummy_list = [ 5, 4, 3, 2, 1, 7, 6, -1, 0]

In [25]:
print(dummy_list)

[5, 4, 3, 2, 1, 7, 6, -1, 0]


In [5]:
print(dummy_list[::-1])

[0, -1, 6, 7, 1, 2, 3, 4, 5]


In [26]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list = dummy_list + dummy_list_2
print(dummy_list)

[5, 4, 3, 2, 1, 7, 6, -1, 0, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [29]:
dummy_dict = {}
for ele in dummy_list:
  if ele not in dummy_dict.keys():
    dummy_dict[ele] = 1
  else:
    dummy_dict[ele] += 1
print(dummy_dict)

{5: 1, 4: 2, 3: 1, 2: 2, 1: 2, 7: 1, 6: 1, -1: 1, 0: 2, 200: 1, 16: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


In [33]:
dummy_list.sort()
print(dummy_list)
dummy_list.sort(reverse=True)
print(dummy_list)

[-1, 0, 0, 1, 1, 2, 2, 3, 4, 4, 5, 6, 7, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0, -1]


In [37]:
x = 200
dummy_list.remove(x)

[90, 45.67, 16, 12.02, 12.01, 9.45, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0, -1]


ValueError: ignored

In [41]:
x = 5
del dummy_list[x]

[90, 45.67, 16, 12.02, 12.01, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0, -1]


In [42]:
dummy_list = []
print(dummy_list)

[]


In [48]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [50]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [54]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a',a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.64933266 0.10821625]
 [0.71282106 0.97982041]]


In [57]:
a  =  np.arange(10)
b  =  np.linspace(0,10, num=6)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


In [58]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [59]:
print(a[0, 1])

2


In [61]:
b[0, 0] = 77
print(a[0, 1])


77


In [62]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]   
row_r2 = a[1:2, :]  

print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape) 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [63]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [64]:
x = np.array([[1,2],[3,4]])

print(np.sum(x)) 
print(np.sum(x, axis=0))  
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [65]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
mask = b%2!=0
print(mask)
print(b[mask])

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [67]:
modified_b = b
modified_b[mask] = -1

print(modified_b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [68]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [71]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
