[View in Colaboratory](https://colab.research.google.com/github/MONA7584908095/Assignment-2/blob/MONA7584908095/MONA7584908095.ipynb)

In [0]:
import random

In [0]:
dummy_list = [random.randrange(10) for i in range(11)]

In [3]:
print(dummy_list)


[9, 9, 6, 0, 8, 9, 5, 1, 1, 7, 7]


In [4]:
print(list(reversed(dummy_list)))

[7, 7, 1, 1, 5, 9, 8, 0, 6, 9, 9]


In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]

In [6]:
#Adding (element wise addition) with original dummy_list (not reversed)
dummy_list = [a+b for a,b in zip(dummy_list,dummy_list_2)]
print(dummy_list)

[11, 209, 22, 4, 9, 9, 14.45, 46.67, 91, 19.009999999999998, 19.02]


In [7]:
dummy_dict = {}
[dummy_dict.update({i:dummy_list.count(i)}) for i in dummy_list]

[None, None, None, None, None, None, None, None, None, None, None]

In [8]:
print(dummy_dict)

{11: 1, 209: 1, 22: 1, 4: 1, 9: 2, 14.45: 1, 46.67: 1, 91: 1, 19.009999999999998: 1, 19.02: 1}


In [9]:
dummy_list_asc = sorted(dummy_list)
print(dummy_list_asc)
dummy_list_desc = sorted(dummy_list, reverse=True)
print(dummy_list_desc)

[4, 9, 9, 11, 14.45, 19.009999999999998, 19.02, 22, 46.67, 91, 209]
[209, 91, 46.67, 22, 19.02, 19.009999999999998, 14.45, 11, 9, 9, 4]


In [10]:
print('Before',dummy_list)

Before [11, 209, 22, 4, 9, 9, 14.45, 46.67, 91, 19.009999999999998, 19.02]


In [12]:

x = 200
# Let's play: try the same with something which is not in the list to get the ValueError
dummy_list.remove(x)


ValueError: ignored

In [13]:
print('Before',dummy_list)
x=2
dummy_list.pop(x)
print('After',dummy_list)

Before [11, 209, 22, 4, 9, 9, 14.45, 46.67, 91, 19.009999999999998, 19.02]
After [11, 209, 4, 9, 9, 14.45, 46.67, 91, 19.009999999999998, 19.02]


In [14]:
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get
x=len(dummy_list) + 1
dummy_list.pop(x)
print(dummy_list)

IndexError: ignored

In [15]:
print('Before',dummy_list)
dummy_list.clear()
print('After',dummy_list)

Before [11, 209, 4, 9, 9, 14.45, 46.67, 91, 19.009999999999998, 19.02]
After []


In [0]:

import numpy as np #import numpy

In [17]:
n = int(input("n: "))
arr = np.tile([1,2,3],3)
print(arr)

n: 121
[1 2 3 1 2 3 1 2 3]


In [18]:
arr = list(range(1,2*10,2))
print(arr, len(arr))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19] 10


In [0]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [20]:
np.intersect1d(a,b)

array([2, 4])

In [0]:
a = np.arange(10)


In [22]:
print(a.reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
#to array
arr = np.array(a)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#to list
lst = arr.tolist()
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.pad(np.zeros((10,10)), 1 ,'constant',constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:

h=int(8/2)
w=int(8/2)
np.tile(np.eye(2),(h,w))
#whats slicing+striding approach?

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [0]:
import numpy as np

In [28]:

a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a)) #print type of a

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

[1 2 3]
<class 'numpy.ndarray'>
(2, 3)
1 2 4


In [29]:
a = np.zeros(shape=(2,2))
b = np.ones(shape = (3,3))
c = np.eye(2)
d = np.full(shape=(3,3), fill_value=5)
e = np.random.random((2,2))

print('a', a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)

a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.12628375 0.03405262]
 [0.72124696 0.92923562]]


In [30]:
a  =  np.arange(10)
b  =  np.linspace(0,10, num=6)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10.]


In [31]:

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2"

b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [32]:

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [33]:

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [34]:
b = np.arange(10)

print(b)

mask = b%2!=0 #perform computations on the list 

print(mask)

print(b[mask]) #applying the mask on the numpy array

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [35]:
modified_b = b
modified_b[mask] = -1

print(modified_b)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [36]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [37]:
a = np.arange(9).reshape(3,3)
print(a)

print(a[[1,0,2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
