<a href="https://colab.research.google.com/github/Suraj1199/Assignment-2/blob/Suraj1199/My_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [76]:
import numpy as np #import numpy
a = np.linspace(1.3,2.5,64)
print (a)

[1.3        1.31904762 1.33809524 1.35714286 1.37619048 1.3952381
 1.41428571 1.43333333 1.45238095 1.47142857 1.49047619 1.50952381
 1.52857143 1.54761905 1.56666667 1.58571429 1.6047619  1.62380952
 1.64285714 1.66190476 1.68095238 1.7        1.71904762 1.73809524
 1.75714286 1.77619048 1.7952381  1.81428571 1.83333333 1.85238095
 1.87142857 1.89047619 1.90952381 1.92857143 1.94761905 1.96666667
 1.98571429 2.0047619  2.02380952 2.04285714 2.06190476 2.08095238
 2.1        2.11904762 2.13809524 2.15714286 2.17619048 2.1952381
 2.21428571 2.23333333 2.25238095 2.27142857 2.29047619 2.30952381
 2.32857143 2.34761905 2.36666667 2.38571429 2.4047619  2.42380952
 2.44285714 2.46190476 2.48095238 2.5       ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [77]:
a = np.array([1,2,3])

x = np.resize(a,12)
print(x)

[1 2 3 1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [78]:
a = np.arange(20)

i = a%2!=0

b = a[i]
print (b)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [79]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = list()
k=0
for value in a:
    for values in b:
        if value == values and value not in c:
            c.append(value)
            break
            
x = np.asarray(a)
x

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

5) Reshape 1d array a to 2d array of 2X5

In [80]:
a = np.arange(10)
print(a)

print(a.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [81]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
#converting to list
b = a.tolist()
print (b)
#again converting it to an array
c =np.asarray(b)
print (c)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [82]:
a = np.zeros(shape = (10,10))
for i in range(0,10):
    for j in range(0,10):
        if i == 0 or i == 9 or j == 0 or j == 9:
            a[i,j] = 1
          
print (a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [83]:
a = np.zeros(shape = (8,8)) 
    # fill with 1 the alternate rows and columns 
  
a[1::2, ::2] = 1
a[::2, 1::2] = 1
      
print (a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
