[View in Colaboratory](https://colab.research.google.com/github/NehaAgarwal2598/Assignment-2/blob/NehaAgarwal2598/NehaAgarwal2598.ipynb)

In [0]:
#Create any random list and assign it to a variable dummy_list

import random

dummy_list = random.sample(range(0, 100), 10)


In [2]:
# print dummy_list

print(dummy_list)

[54, 59, 17, 71, 78, 50, 51, 16, 82, 1]


In [3]:
#Reverse dummy_list and print

dummy_list.reverse()
print(dummy_list)

[1, 82, 16, 51, 50, 78, 71, 17, 59, 54]


In [4]:
#Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
print(dummy_list+dummy_list_2)

[1, 82, 16, 51, 50, 78, 71, 17, 59, 54, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
# Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values.

dummy_dict={i:dummy_list.count(i) for i in set(dummy_list)}

In [6]:
#print dummy_dict
print (dummy_dict)

{1: 1, 71: 1, 78: 1, 16: 1, 17: 1, 82: 1, 51: 1, 50: 1, 54: 1, 59: 1}


In [7]:
#Sort dummy_list in ascending order as well as descending order and print the changed lists
#ASCENDING ORDER 
dummy_list.sort()
print(dummy_list)

#DESCENDING ORDER
dummy_list.sort(reverse=True)
print(dummy_list)


[1, 16, 17, 50, 51, 54, 59, 71, 78, 82]
[82, 78, 71, 59, 54, 51, 50, 17, 16, 1]


In [8]:
# Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

x = 200
dummy_list.remove(x)

# Let's play: try the same with something which is not in the list to get the ValueError

x=300

dummy_list.remove(x)

ValueError: ignored

In [9]:
#Remove the item at position x. x is any random integer
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get

x=20
dummy_list.remove(dummy_list[x])

x=len(dummy_list)+5
dummy_list.remove(dummy_list[x])


IndexError: ignored

In [10]:
 #Let's clean everything clear the list and then print
dummy_list.clear()
print(dummy_list)

[]


In [11]:
#) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

import numpy as np

np.linspace(-1.3, 25, num=64)

array([-1.3       , -0.88253968, -0.46507937, -0.04761905,  0.36984127,
        0.78730159,  1.2047619 ,  1.62222222,  2.03968254,  2.45714286,
        2.87460317,  3.29206349,  3.70952381,  4.12698413,  4.54444444,
        4.96190476,  5.37936508,  5.7968254 ,  6.21428571,  6.63174603,
        7.04920635,  7.46666667,  7.88412698,  8.3015873 ,  8.71904762,
        9.13650794,  9.55396825,  9.97142857, 10.38888889, 10.80634921,
       11.22380952, 11.64126984, 12.05873016, 12.47619048, 12.89365079,
       13.31111111, 13.72857143, 14.14603175, 14.56349206, 14.98095238,
       15.3984127 , 15.81587302, 16.23333333, 16.65079365, 17.06825397,
       17.48571429, 17.9031746 , 18.32063492, 18.73809524, 19.15555556,
       19.57301587, 19.99047619, 20.40793651, 20.82539683, 21.24285714,
       21.66031746, 22.07777778, 22.4952381 , 22.91269841, 23.33015873,
       23.74761905, 24.16507937, 24.58253968, 25.        ])

In [0]:
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3



In [12]:
#Create an array of the first 10 odd integers.

np.arange(1,20,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
# Find intersection of a and b
# expected output array([2, 4])
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [0]:
#5) Reshape 1d array a to 2d array of 2X5

a = np.arange(10)
b = np.reshape(a, (-1, 5))


In [20]:
# Create a numpy array to list and vice versa

#a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

#numpy array to list 
a.tolist()

#list to numpy array

from numpy import array
array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

x = np.ones((10,10))

x[1:-1,1:-1] = 0

In [0]:
# Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
