[View in Colaboratory](https://colab.research.google.com/github/subhrajyotidasgupta/Assignment-2/blob/subhrajyotidasgupta/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [9]:
a = np.array([1,2,3])
print(np.tile(a,3))

[1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [12]:
a = np.arange(20)
mask = a%2!=0
a[mask]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4) Find intersection of a and b

In [15]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

5) Reshape 1d array a to 2d array of 2X5

In [17]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

6) Create a numpy array to list and vice versa

In [18]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.array(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [33]:
a = np.zeros(shape=(10,10))
a[0,:]=a[:,0]=a[9,:]=a[:,9] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

,8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [52]:
a = np.zeros(shape=(8,8))
a[::2,::2]=1
a[1::2,1::2]=1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])