[View in Colaboratory](https://colab.research.google.com/github/rrb8319/Assignment-2/blob/master/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [5]:
a=np.arange(1,4)
print(a)

[1 2 3]


3) Create an array of the first 10 odd integers.

In [8]:
a= np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [0]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [11]:
print(list(set(a) & set(b)))

[2, 4]


5) Reshape 1d array a to 2d array of 2X5

In [16]:
a = np.arange(10).reshape(2,5)

print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [23]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

a=np.array(a)
print(type(a))

a=a.tolist()
print(type(a))



<class 'numpy.ndarray'>
<class 'list'>


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [35]:
a = np.zeros(shape=(10,10))

for i in range(10) :
  for j in range(10) :
    if i==0 or j==0 or i==9 or j==9 :
       a[i,j]=1
print(a)        
   

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [38]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
