[View in Colaboratory](https://colab.research.google.com/github/sayanmondal31/Assignment-2/blob/sayanmondal31/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [4]:
import numpy as np #import numpy
s=np.random.uniform(-1.3,2.5,64)
print(s)


[-0.92847835  2.16635285  1.58173917  1.61273914  1.60990939 -1.02543714
  0.46532421  1.10440527  1.89593727 -1.1124212  -0.54577597  0.42978527
  1.61450955  0.92872055  2.23775387  0.19406846  0.94577686  2.20516991
  0.73545259  1.15513843  2.32342577  2.10919311 -0.26367905  1.52965673
  0.72426996 -0.90306365  1.93898394  2.32504855 -0.1252837   2.4056438
  1.43768491 -0.45177326  0.53679716 -0.06122403  0.88628156 -0.2928114
 -0.55744346  1.94641126 -1.19942371 -1.05753952  0.7124453   1.77629621
  1.39047877  1.21402328  2.0579934   0.68490074 -0.8244926   2.2477931
  1.1547666  -0.86531884  2.41155762  0.32280929 -0.58664679  1.00839942
  2.42928925 -0.76051337  1.81138519  2.0128754  -0.90171955  0.88895307
  2.00585918 -0.46717285 -1.15523489 -0.86037499]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [5]:
m=np.full(shape=(3,3),fill_value=[1,2,3])
print(m)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


3) Create an array of the first 10 odd integers.

In [6]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


4) Find intersection of a and b

In [7]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
s = [val for val in a if val in b]
print(s)

[2, 2, 4, 4]


5) Reshape 1d array a to 2d array of 2X5

In [9]:
a = np.arange(10)
print("1d",a)
a = np.arange(10).reshape(2,5)
print("2d",a)

1d [0 1 2 3 4 5 6 7 8 9]
2d [[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [12]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("making list",list(a))
a.reverse()
print("vice versa of list",list(a))


making list [1, 2, 3, 4, 5, 6, 7, 8, 9]
vice versa of list [9, 8, 7, 6, 5, 4, 3, 2, 1]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [19]:
n=np.zeros(shape=(10,10))
print("original array")
print(n)
n=np.ones(shape=(10,10))
print("frame with ones")
n[1:-1,1:-1] = 0
print(n)


original array
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
frame with ones
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [22]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
