# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [33]:
n = 4
arr = np.zeros(shape=(n,3),dtype=int)
for i in range(n):
  arr[i][0] = 1
  arr[i][1] = 2
  arr[i][2] = 3
  
print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


3) Create an array of the first 10 odd integers.

In [34]:
array_odd = np.arange(1,20,2)
print(array_odd)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [35]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [36]:
a = np.arange(10)
print(a.shape)
a = a.reshape(2,5)
print(a.shape)

(10,)
(2, 5)


6) Create a numpy array to list and vice versa

In [37]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(type(a))
new_arr = np.array(a)
print(type(new_arr))

<class 'list'>
<class 'numpy.ndarray'>


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [38]:
arr = np.zeros(shape = (10,10),dtype=int)
def border(arr,min,max,bor):
  arr[min, :] = 1
  arr[:, min] = 1
  arr[max, :] = 1
  arr[:, max] = 1
  return arr

arr = border(arr,0,9,1)
print(arr)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [41]:
import numpy as np
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
