[View in Colaboratory](https://colab.research.google.com/github/imsayn/Assignment-2/blob/imsayn/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [9]:
new_array= np.arange(9).reshape(3,3)
new_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3) Create an array of the first 10 odd integers.

In [5]:
one=np.arange(20)
int_ger=one%2 !=0
final=one[int_ger]
print(final)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [11]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= a-b==0
d=a[c]
print(d)

[2 2 4 4]


5) Reshape 1d array a to 2d array of 2X5

In [13]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

6) Create a numpy array to list and vice versa

In [31]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b= np.array(a)
print(b, "\n")
c=b.tolist()
print(c)





[1 2 3 4 5 6 7 8 9] 

[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [36]:
zero=np.zeros(shape=(10,10))
zero[0]=1
zero[9]=1
zero[:,0]=1
zero[:,9]=1

zero

  

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [38]:
zero= np.arange(100).reshape(10,10)
k=zero%2 !=0
l=zero%2 ==0
zero[k]=1
zero[l]=0
zero



array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])