[View in Colaboratory](https://colab.research.google.com/github/ashi31/Assignment-2/blob/ashi31/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy
np.linspace(-1.3,2.5,64)

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [0]:
n = input("enter n: ")
n = int(n)
a = np.array([1, 2, 3])
a = np.resize(a, 3* n)

print(a)

3) Create an array of the first 10 odd integers.

In [9]:
n = input("enter n: ")
n = int(n)
odd = np.arange(1,2*n,2)
print(odd)

enter n: 10
[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [20]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

intersection = list(set(filter(lambda i: i in filter(lambda j:j , b) , a)))
print(np.array(intersection))

# or

intersect = np.intersect1d(a,b)
print(intersect)

[2 4]
[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [21]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [22]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

arr = np.array(a)
print (arr)

listc = list(arr)
print(listc)


[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [4]:
a = np.ones(shape = (12,12))
a[1:11,1:11] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [11]:
a = np.ones(shape = (8,8))
a[0::2,1::2] = 0
a[1::2,0::2] = 0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
