[View in Colaboratory](https://colab.research.google.com/github/shadow9d/Assignment-2/blob/shadow9d/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [2]:
n = 4
arr = np.zeros(shape=(n,3))
for i in range(n):
  arr[i][0] = 1
  arr[i][1] = 2
  arr[i][2] = 3
  
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


3) Create an array of the first 10 odd integers.

In [3]:
array_odd = np.arange(1,20,2)
print(array_odd)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [4]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [10]:
a = np.arange(10)
print(a.shape)
a = a.reshape(2,5)
print(a.shape)

(10,)
(2, 5)


6) Create a numpy array to list and vice versa

In [14]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(type(a))
new_arr = np.array(a)
print(type(new_arr))

<class 'list'>
<class 'numpy.ndarray'>


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [24]:
arr = np.zeros(shape = (10,10))
def border(arr,min,max,bor):
  for i in range(max + 1):
    arr[min][i] = bor
    arr[i][min] = bor
    arr[max][i] = bor
    arr[i][max] = bor
  return arr

arr = border(arr,0,9,1)
#print(arr)

arr = np.zeros(shape = (10,10))
print(arr[1:3,1:5])
#print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.