[View in Colaboratory](https://colab.research.google.com/github/k-manisha/Assignment-2/blob/k-manisha/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [2]:
import numpy as np #import numpy
#a = np.arange(-1.3,2.5,0.06)
a=np.linspace(-1.3,2.5,64+1)
a=list(map(lambda x,y: [x,y] , a,a[1:]))
a=np.array(a)
print(a)

[[-1.3      -1.240625]
 [-1.240625 -1.18125 ]
 [-1.18125  -1.121875]
 [-1.121875 -1.0625  ]
 [-1.0625   -1.003125]
 [-1.003125 -0.94375 ]
 [-0.94375  -0.884375]
 [-0.884375 -0.825   ]
 [-0.825    -0.765625]
 [-0.765625 -0.70625 ]
 [-0.70625  -0.646875]
 [-0.646875 -0.5875  ]
 [-0.5875   -0.528125]
 [-0.528125 -0.46875 ]
 [-0.46875  -0.409375]
 [-0.409375 -0.35    ]
 [-0.35     -0.290625]
 [-0.290625 -0.23125 ]
 [-0.23125  -0.171875]
 [-0.171875 -0.1125  ]
 [-0.1125   -0.053125]
 [-0.053125  0.00625 ]
 [ 0.00625   0.065625]
 [ 0.065625  0.125   ]
 [ 0.125     0.184375]
 [ 0.184375  0.24375 ]
 [ 0.24375   0.303125]
 [ 0.303125  0.3625  ]
 [ 0.3625    0.421875]
 [ 0.421875  0.48125 ]
 [ 0.48125   0.540625]
 [ 0.540625  0.6     ]
 [ 0.6       0.659375]
 [ 0.659375  0.71875 ]
 [ 0.71875   0.778125]
 [ 0.778125  0.8375  ]
 [ 0.8375    0.896875]
 [ 0.896875  0.95625 ]
 [ 0.95625   1.015625]
 [ 1.015625  1.075   ]
 [ 1.075     1.134375]
 [ 1.134375  1.19375 ]
 [ 1.19375   1.253125]
 [ 1.253125

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [0]:
a= np.array([1,2,3])
n=5
a=np.resize(a,3*n)
print(a)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [0]:
a=np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [0]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
"""
c=[]
for x in set(a):
  if x in set(b):
    c.append(x)
print(np.array(c))
"""
c=np.intersect1d(a,b)
print(c)

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10)
a=a.reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [0]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a= np.array(a)
print(a)
#converting numpy array to list
a=a.tolist()
print(a)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [19]:
a=np.zeros((10,10))
print(a)
print()
a[[0,9],:]=1
a[:,[0,9]]=1
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [47]:
a= np.ones((8,8))
a[0::2,0::2]=0
a[1::2,1::2]=0
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
