<a href="https://colab.research.google.com/github/loneWolf148/Assignment-2/blob/loneWolf148/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [3]:
cyclic_array = np.resize([1,2,3], 3* int(input()))
print(cyclic_array)

6
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [4]:
odds = np.arange(1,20,2)
print(odds)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [5]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
intersection = np.intersect1d(a,b)
print(intersection)

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [6]:
a = np.arange(10)
reshaped_array = a.reshape((2,5))
print(reshaped_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [7]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
numpy_array = np.array(a)
print(numpy_array)
converted_list = list(numpy_array)
print(converted_list)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [8]:
zeros = np.zeros((10,10))
zeros[0] = 1
zeros[9] = 1
zeros[:,0] = 1 
zeros[:,9] = 1
print(zeros)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [22]:
checkerboard = np.zeros((8,8))
checkerboard[::,::2] = 1
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
