In [0]:
#Import numpy
import numpy as np

In [12]:
#1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions
a=np.linspace(-1.3,2.5,64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [15]:
#2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

x=np.array([1,2,3])
y=np.resize(x,9)
print(y)

[1 2 3 1 2 3 1 2 3]


In [19]:
#3) Create an array of the first 10 odd integers.
a=np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [24]:
#4) Find intersection of a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#c = np.array([i for i in a if i in b])
c=np.intersect1d(a,b)
print(c)

[2 4]


In [28]:
#5) Reshape 1d array a to 2d array of 2X5
a = np.arange(10).reshape((2,5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [43]:
#Create a numpy array to list and vice versa
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a=np.asarray(a)
print(a)
b=a
b=b.tolist()
print(b)


[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [50]:
#7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.
a=np.zeros((10,10))
i=0
while(i<10):
  a[0][i]=1
  a[9][i]=1
  a[i][0]=1
  a[i][9]=1
  i=i+1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [54]:
#8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
