[View in Colaboratory](https://colab.research.google.com/github/nehasinghh/Assignment-3/blob/nehasinghh/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [2]:
import numpy as np #import numpy
s=np.random.uniform(-1.3,2.5,64)
print(s)

[-0.52726714  0.76172836  2.42200484  0.20041298  2.25045397  2.01213916
  0.87132336  0.86536254  2.46991562  0.13029733  2.16912735 -0.98970112
 -0.06646756  1.63814014  0.85666336 -0.21084126  0.11536319  1.10469075
 -0.20645471  1.83102684  1.10407741  1.69929997  0.84719492  1.15335626
  1.82018755  0.07504611  1.44869711  0.091504    0.51646653  1.37153711
  2.00173955 -1.10551868  0.94457653 -0.0954746  -0.02589314 -0.63362223
 -0.83194216  0.8923438   1.00253444 -1.12957086  0.81854463 -0.83808216
  0.37346844  0.81405416  1.16822532  1.865022    0.2153456   2.08633775
  0.68694379 -0.52227196 -0.09169795  2.44323553  1.71886126  1.66935016
  0.04971489  1.10883661 -0.8014794   0.40172164  1.66366659  0.78375277
  2.31693868 -0.47151038 -0.16585436 -0.68238863]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [3]:
s=np.full(shape=(3,3),fill_value=[1,2,3])
print(s)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


3) Create an array of the first 10 odd integers.

In [4]:
d=np.array([1,3,5,7,9])
print(d)

[1 3 5 7 9]


4) Find intersection of a and b

In [5]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
p=[val for val in a if val in b]
print(p)

[2, 2, 4, 4]


5) Reshape 1d array a to 2d array of 2X5

In [8]:
a = np.arange(10)
print("1d",a)
a = np.arange(10).reshape(2,5)
print("2d",a)

1d [0 1 2 3 4 5 6 7 8 9]
2d [[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [9]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("making list",list(a))
a.reverse()
print("vise versa of list",list(a))


making list [1, 2, 3, 4, 5, 6, 7, 8, 9]
vise versa of list [9, 8, 7, 6, 5, 4, 3, 2, 1]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [11]:
n=np.zeros(shape=(10,10))
print("original array")
print(n)
n=np.ones(shape=(10,10))
print("frame with ones")
n[1:-1,1:-1]=0
print(n)

original array
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
frame with ones
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [12]:
s=np.ones((3,3))
print("Checkerboard Pattern")
s=np.zeros((8,8),dtype=int)
s[1::2,::2]=1
s[::2,1::2]=1
print(s)

Checkerboard Pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
