[View in Colaboratory](https://colab.research.google.com/github/subhadeep-123/Assignment-2/blob/subhadeep-123/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [1]:
import numpy as np #import numpy
s=np.random.uniform(-1.3,2.5,64)
print(s)

[ 0.38878314 -0.49777868  1.41713662 -0.25303383 -1.18385634 -0.2757895
  1.43680187  0.59220279  0.25374688 -0.72194508  0.78036303  2.14632699
  1.61037151  1.14730023  1.13767392  0.05070785  0.11760413 -0.81384082
  2.13191724  1.04601306  1.76337155  1.06013152  0.28944169  1.69302789
 -0.36597327 -0.59833645  1.28016074 -0.28363818  1.81485658  0.9728496
  1.42686746  0.45232407  0.40394849 -0.7947052   2.48764125  0.24247037
  2.06028828 -0.57478979  1.59295111  0.79627711 -0.23921452 -1.18693366
 -0.92524744  0.0839297   2.10851601 -0.76999558  0.53614925  2.46324992
  0.06765006  2.05649882 -1.06988303  1.83013442 -0.5583051  -1.18578655
  0.86962099  2.25122272  1.86295407  1.77055828  1.48040811  2.29916068
 -1.03295015 -0.686019    1.21031915  1.49164883]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [2]:
m=np.full(shape=(3,3),fill_value=[1,2,3])
print(m)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


3) Create an array of the first 10 odd integers.

In [3]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


4) Find intersection of a and b

In [4]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
s=[val for val in a if val in b]
print(s)

[2, 2, 4, 4]


5) Reshape 1d array a to 2d array of 2X5

In [5]:
a = np.arange(10)
print("1d",a)
a = np.arange(10).reshape(2,5)
print("2d",a)

1d [0 1 2 3 4 5 6 7 8 9]
2d [[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [6]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("making list",list(a))
a.reverse()
print("Vice versa of list", list(a))


making list [1, 2, 3, 4, 5, 6, 7, 8, 9]
Vice versa of list [9, 8, 7, 6, 5, 4, 3, 2, 1]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [8]:
n=np.zeros(shape=(10,10))
print("Oiginal array")
print(n)
n=np.ones(shape=(10,10))
print("frame with ones")
n[1:-1,1:-1]=0
print(n)

Oiginal array
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
frame with ones
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [10]:
x=np.ones((3,3))
print("Checkerboard pattern:")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
