[View in Colaboratory](https://colab.research.google.com/github/MonojitBag/Assignment-2/blob/MonojitBag/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [2]:
import numpy as np #import numpy
s=np.random.uniform(-1.3,2.5,64)
print(s)

[-0.21060772  0.79312826  1.4734058   0.48079952  1.29843904 -0.96115442
 -0.04434021  2.28235959  0.20789686  1.81820813  1.71206276  0.07943778
  2.46395034  0.6025707  -0.58656078  2.28309658 -0.13637224 -0.74144344
  1.11227751  1.87713202  2.14193442 -0.0099723  -0.63646606  0.03415162
  1.34034212 -0.97783931  0.75486278  0.85980073  0.15460385  2.43437119
  1.92758403  0.33248899  1.74054777 -0.56080518  1.92443702  0.03286954
  1.27740863  0.4849546   2.45805457  1.79206334  0.88642255  0.2943211
  0.01908824  1.36954157  0.80996875  0.76325266  0.49401712  1.49577459
  1.83106661 -0.34946721  0.55900233  0.62205716 -1.10765401  1.53224592
 -0.03993473  0.10816507 -0.90543584  2.4737842   0.48199609 -0.59170816
 -0.03464182  1.8829989   2.42661432  1.76294743]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [3]:
m=np.full(shape=(3,3),fill_value=[1,2,3])
print(m)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


3) Create an array of the first 10 odd integers.

In [4]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


4) Find intersection of a and b

In [5]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
s=[val for val in a if val in b]
print(s)

[2, 2, 4, 4]


5) Reshape 1d array a to 2d array of 2X5

In [6]:
a = np.arange(10)
print("1d",a)
a= np.arange(10).reshape(2,5)
print("2d",a)

1d [0 1 2 3 4 5 6 7 8 9]
2d [[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [7]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("making list",list(a))
a.reverse()
print("making list vice versa",list(a))


making list [1, 2, 3, 4, 5, 6, 7, 8, 9]
making list vice versa [9, 8, 7, 6, 5, 4, 3, 2, 1]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [8]:
n=np.zeros(shape=(10,10))
print("original array")
print(n)
n=np.ones(shape=(10,10))
print("frame with ones")
n[1:-1,1:-1]=0
print(n)

original array
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
frame with ones
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [9]:
x=np.ones((3,3))
print("checkerboard pattern:")
x= np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
