[View in Colaboratory](https://colab.research.google.com/github/AmbujaAK/Assignment-2/blob/AmbujaAK/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [69]:
x = np.array([1,2,3])
y = np.resize(x,12)

print(y)

[1 2 3 1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [9]:
b = np.arange(1,20,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [16]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
print(c)

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [18]:
a = np.arange(10)
print(a)
print('---------')
a = np.arange(10).reshape(2,5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
---------
[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [21]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(a)
print(a)
print(type(a))

a = list(a)
print(a)
print(type(a))


[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [39]:
a = np.zeros((10,10))
print(a)
print('      ***** with frame *****')
a[0] = a[9] = 1
a[:,0] = a[:,9] = 1
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
      ***** with frame *****
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [68]:
chess = np.arange(64)

mask1 = chess%2 != 0
mask2 = chess%2 == 0

new_chess = chess
new_chess[mask1] = 1
new_chess[mask2] = 0

print(new_chess)

a0 = new_chess[:8]
a1 = new_chess[8:16]
a2 = new_chess[16:24]
a3 = new_chess[24:32]
a4 = new_chess[32:40]
a5 = new_chess[40:48]
a6 = new_chess[48:56]
a7 = new_chess[56:64]

print('    ***** Chess board *****')
x = np.array([a0,a1[::-1],a2,a3[::-1],a4,a5[::-1],a6,a7[::-1]])
print(x)


[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
    ***** Chess board *****
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
