# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [33]:
import numpy as np #import numpy
s = np.random.uniform(-1.3,2.5,64)
print(s)

[ 2.01949375  0.24488385  1.10616472  1.10275403  0.39531167  0.23673637
  2.14598971 -0.09173076  2.16672262  1.81091938  0.00565215  1.05000008
  0.47556343 -0.92087234  2.42517041  0.53391398  1.88622074 -1.15772936
  0.21105265 -0.11811615  2.38646807 -0.10930081 -0.53306559  1.92749905
  0.01020341  1.04470736  0.13537357 -1.09048015  0.38561263  1.37644049
  1.14206756  1.48095337  2.17869473  2.49409381  1.02486021  0.74003063
 -0.1071404  -0.21530303  0.67589152 -0.49124014  0.5809801  -0.47563336
  0.37069972 -0.6455856   0.8378141  -0.09770696  2.17771274 -0.8329354
 -0.719457    0.13325561 -0.85632437  0.799063   -0.11569906  2.28837746
  2.23002743  1.92321613 -0.30916734  0.34377629  1.31298422 -0.11318277
  0.80927591 -1.29320411 -0.62136114  1.32573031]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [32]:
x = np.array([1, 2, 3])

y = np.resize(x, 9)
print(y)

[1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [25]:
arr = np.array(range(1,20,2))
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [26]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [28]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [30]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

#Array to npArray
npArray= np.array(a)
print(npArray)
# npArray to List
Array = list(npArray)
print(Array)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [24]:
arr=np.zeros((10,10))
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 1)
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [36]:
def build_checkerboard(w, h) :
      re = np.r_[ w*[0,1] ]             
      ro = np.r_[ w*[1,0] ]             
      return np.row_stack(h*(re, ro))
    
checkerboard = build_checkerboard(8, 8)    
print(checkerboard)    

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]
