[View in Colaboratory](https://colab.research.google.com/github/Debjit08/Assignment-2/blob/Debjit08/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy
b=np.linspace(-1.2,2.5, num=64)

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [27]:
n=int(input("Enter the size:"))
a=np.arange(1,4)
a=np.resize(a,3*n)
print(a)

Enter the size:3
[1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [0]:
a=np.arange(20)
modified_a = a[a%2!=0]

4) Find intersection of a and b

In [6]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10).reshape(2,5)

6) Create a numpy array to list and vice versa

In [13]:
a =np.arange(1,10)
a=a.tolist()
np.asarray(a)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [20]:
a = np.zeros(shape=(10,10))
print("Initialization")
print(a) #after creation of the array
for i in range(10):
  a[0,i]=1
  a[i,0]=1
  a[i,9]=1
  a[9,i]=1
print("Framing:")
print(a) #after framing:

Initialization
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Framing:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [29]:
b=np.ones((3,3))
print("Checkerboard pattern:")
b=np.zeros((8,8),dtype=int)
b[1::2,::2]=1
b[::2,1::2]=1
print(b)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
