[View in Colaboratory](https://colab.research.google.com/github/Sayan46/Assignment-2/blob/Sayan46/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [2]:
import numpy as np 
s = np.random.uniform(-1.3,2.5,64)
print(s)


[ 1.29714042  0.05382672  2.11603915  0.46257789  0.39152661 -0.14922545
  1.6112405   1.97758278 -1.23275156 -0.43644515 -0.83081985 -0.20409018
  0.9461046  -1.21474827  1.0501915  -0.65469646  0.21974205  2.0357349
 -0.0210625   0.2303843   0.03695057 -0.22360614  1.57105111  0.44567277
 -0.31814993 -0.33186138  1.83457452  0.64501397 -0.72027239  0.31311365
  2.22288395 -0.43783351 -0.5531905  -0.11004932  0.04434198  1.6141596
  1.29484714 -0.88055521  0.90784743  2.24186256  0.6197379   1.82008514
  2.14463852  2.4116079   0.80386049 -0.43050777  1.02151095  0.89904801
  1.44200865  0.00406608  1.20474749  1.03238049 -0.79745927  0.13132264
 -0.04273136 -0.11766145 -0.8821126   1.15447771  2.12783845  0.59703821
  0.49830412  0.71234306  1.27832384  1.6935996 ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [3]:
n=3
x = np.array([1,2,3])
y = np.tile(x,n)
print(y)

[1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [11]:
a=np.array([1,3,5,7,9,11,13,15,17,19])
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [8]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [9]:
new = np.reshape(a,(2,5))
print(new)

[[1 2 3 2 3]
 [4 3 4 5 6]]


6) Create a numpy array to list and vice versa

In [12]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b=(a.tolist())
print(b)
a1=np.asarray(b)
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [16]:
d =np.ones(shape=(11,11))
d[1:-1,1:-1] = 0
print(d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [3]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
