[View in Colaboratory](https://colab.research.google.com/github/alishashaw439/Assignment-2/blob/alishashaw439/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [1]:
import numpy as np #import numpy
s=np.random.uniform(-1.3,2.5,64)
print(s)

[ 0.99916173  1.44577775 -0.91111002 -0.04021482  0.53296654 -0.38086001
  1.28344172  1.67132791  2.32215226  1.86095606  1.00334668  1.69840683
 -0.68339134  1.8670723  -1.24987688  0.17772064  0.42090757  2.39462716
  1.19757949  0.51937989 -1.12754575 -0.32126093  2.47185444  0.29079335
 -0.53413132 -0.40789562 -1.01057638  2.18168026 -1.17597753 -0.99200005
 -0.95628562  1.68390668  0.14380228  0.05880454  0.87517923 -0.14909405
  2.03522053  0.41595551  1.92824439  1.06266402  1.66236382  1.07493037
  0.29188334 -0.69348233  0.08846541  0.50558505  1.78653059  0.91789151
  0.66390236  2.11623076  1.27494456 -0.53145188  1.83465851  1.11918454
 -0.63162805 -0.74866153 -0.61440454  0.72586693  1.86773439 -0.4834888
 -0.35440805 -0.2172648  -0.75678147  1.24233168]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [2]:
m=np.full(shape=(3,3),fill_value=[1,2,3])
print(m)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


3) Create an array of the first 10 odd integers.

In [3]:
s=np.array([1,3,5,7,9])
print(s)

[1 3 5 7 9]


4) Find intersection of a and b

In [5]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
s = [val for val in a if val in b]
print(s)

[2, 2, 4, 4]


5) Reshape 1d array a to 2d array of 2X5

In [7]:
a = np.arange(10)
print('1d',a)
a = np.arange(10).reshape(2,5)
print('2d',a)

1d [0 1 2 3 4 5 6 7 8 9]
2d [[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [8]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print('list',list(a))
a.reverse()
print('vice versa',list(a))


list [1, 2, 3, 4, 5, 6, 7, 8, 9]
vice versa [9, 8, 7, 6, 5, 4, 3, 2, 1]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [9]:
n = np.zeros(shape=(10,10))
print('original array')
print(n)
n=np.ones(shape=(10,10))
print('frame with ones')
n[1:-1,1:-1] = 0
print(n)

original array
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
frame with ones
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [10]:
y = np.ones((3,3))
print('checkboard pattern')
y = np.zeros((8,8),dtype=int)
y[1::2,::2] = 1
y[::2,1::2] = 1
print(y)

checkboard pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
