[View in Colaboratory](https://colab.research.google.com/github/amartyabhattacharya/Assignment-2/blob/amartyabhattacharya/Numpy_Exercises.ipynb)

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [2]:
import numpy as np #import numpy
uni_sub = np.linspace(-1.3, 2.5, 65)
print(uni_sub)

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [3]:
n = int(input())
a = np.array([1,2,3])
b = np.resize(a, 3*n)
print(b)

3
[1 2 3 1 2 3 1 2 3]


3) Create an array of the first 10 odd integers.

In [5]:
a = np.arange(2*10)
mask = a % 2 == 1
b = a[mask]
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [7]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
print(c)

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [12]:
a = np.arange(10)
a = a.reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [13]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = np.array(a)
print(b)
c = b.tolist()
print(c)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [15]:
a = np.ones((11,11), dtype = int)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [14]:
a = np.zeros((8,8), dtype = int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
