[View in Colaboratory](https://colab.research.google.com/github/ravikish/Assignment-2/blob/ravikish/Numpy_Exercise.ipynb)

In [0]:
import numpy as np

In [4]:
subdiv = np.linspace(-1.3,2.5,64)
print(subdiv)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [0]:
n=5

In [7]:
arr=np.resize([1,2,3],3*n)
print(arr)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [8]:
o_array=np.arange(1,2*10+1,2)
print(o_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [9]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [10]:
a = np.arange(10)
print(a.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = np.array(a)
print(type(b))
b = list(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [12]:
a = np.zeros((10,10), dtype=np.int8)
b = np.pad(a,1,'constant',constant_values=1)
print(b)

[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]


In [14]:
checkerboard = np.zeros((8,8), dtype=np.int8)
checkerboard[::2,::2] = 1
checkerboard[1::2,1::2] = 1
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
