In [0]:
#Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

import numpy as np

a = np.linspace(-1.3, 2.5, num= 25)
print(a)

In [0]:
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3


n = 4
a = np.array([1, 2, 3])
a = np.resize(a, 3*n)
print(a)

In [0]:
#Create an array of the first 10 odd integers.

a = np.arange(1, 20, 2)
print(a)

In [10]:
#Find intersection of a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)
print(c)

[2 4]


In [18]:
# Reshape 1d array a to 2d array of 2X5

a = np.arange(10)
b = np.resize(a, (2, 5))
#b = a.reshape(2, 5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
#Create a numpy array to list and vice versa

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]    #list
b = np.array(a)                    #to array
print(b)                           #array
c = list(b)                        #to list
print(c)                           #list again


[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [0]:
#Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

a = np.zeros((10, 10))
a[0, :] = a[-1, :] = 1
a[:, 0] = a[:, -1] = 1
print(a)

#alternatively
"""
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

"""

In [31]:
#Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

a = np.ones((8, 8))
a[1::2, ::2] = 0
a[::2, 1::2] = 0
print(a)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
