####List Exercise

1) Create any random list and assign it to a variable dummy_list and print

In [4]:
import random
dummy_list = random.sample(range(100), 10)

dummy_list

[18, 39, 93, 21, 87, 90, 75, 84, 86, 34]

2)Reverse and print

In [5]:
dummy_list.reverse()

dummy_list

[34, 86, 84, 75, 90, 87, 21, 93, 39, 18]

Add dumy_list_2 to dummy_list

In [6]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]

dummy_list = dummy_list + dummy_list_2

dummy_list

[34,
 86,
 84,
 75,
 90,
 87,
 21,
 93,
 39,
 18,
 2,
 200,
 16,
 4,
 1,
 0,
 9.45,
 45.67,
 90,
 12.01,
 12.02]

Creating a dictionary to store elements as keys and frequency as values

In [8]:
dummy_dict = {}

for i in dummy_list:
  if i not in dummy_dict.keys():
    dummy_dict[i] = 1
  else:
    dummy_dict[i] += 1
    
dummy_dict


{0: 1,
 1: 1,
 2: 1,
 4: 1,
 9.45: 1,
 12.01: 1,
 12.02: 1,
 16: 1,
 18: 1,
 21: 1,
 34: 1,
 39: 1,
 45.67: 1,
 75: 1,
 84: 1,
 86: 1,
 87: 1,
 90: 2,
 93: 1,
 200: 1}

Sort the list

In [9]:
dummy_list.sort()

print(dummy_list)

[0, 1, 2, 4, 9.45, 12.01, 12.02, 16, 18, 21, 34, 39, 45.67, 75, 84, 86, 87, 90, 90, 93, 200]


Reverse the list

In [10]:
dummy_list.reverse()
print(dummy_list)

[200, 93, 90, 90, 87, 86, 84, 75, 45.67, 39, 34, 21, 18, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


Delete an element by value from a list

In [12]:
x = 200

for i  in dummy_list:
  if i == x:
    dummy_list.remove(i)
    break
    
print(dummy_list)


[93, 90, 90, 87, 86, 84, 75, 45.67, 39, 34, 21, 18, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


Delete an element by  location

In [15]:
x = random.randint(1,10)

print(x)

dummy_list.pop(x)

print(dummy_list)

1
[93, 90, 87, 86, 84, 45.67, 39, 34, 21, 18, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


Print the list

In [16]:
print(dummy_list)

[93, 90, 87, 86, 84, 45.67, 39, 34, 21, 18, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


####Numpy Exercise

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [17]:
import numpy as np #import numpy


arr = np.linspace(-1.3,2.5,64)
print(arr)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [19]:
a = np.array([1,2,3])

n = random.randint(1,10)

b = np.resize(a,n)

print(b)

[1 2 3 1 2]


3) Create an array of the first 10 odd integers.

In [0]:
a = np.arange(30)

mask = a%2!=0

a = a[mask]

a = np.resize(a,10)

In [22]:
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10)

a = a.reshape((2,5))

In [27]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [29]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

print(type(a))

a = np.asarray(a)

print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [30]:
b = np.arange(10)

print(type(b))

b = b.tolist()

print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [31]:
z = np.zeros((10,10))
# print(z)

z[:,0]=1
z[:,9]=1
z[0,:]=1
z[9,:]=1

print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [32]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
