# Exercise - List

1) Create  any random list and assign it to a variable dummy_list

In [0]:
dummy_list= [0,1,1,2,3,5,8]

2) print dummy_list

In [0]:
print (dummy_list)


[0, 1, 1, 2, 3, 5, 8]


3) Reverse dummy_list and print

In [0]:
dummy_list.reverse()
print (dummy_list)

[8, 5, 3, 2, 1, 1, 0]


4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list= dummy_list+dummy_list_2
print (dummy_list)

[8, 5, 3, 2, 1, 1, 0, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values. 

In [0]:

dummy_dict={keys:dummy_list.count(keys) for keys in dummy_list}

6) print dummy_dict

In [0]:
print(dummy_dict)


{8: 1, 5: 1, 3: 1, 2: 2, 1: 3, 0: 2, 200: 1, 16: 1, 4: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


7) Sort dummy_list in ascending order as well as descending order and print the changed lists 

In [0]:
dummy_list.sort()
print (dummy_list)
dummy_list.sort(reverse=True)
print (dummy_list)

[0, 0, 1, 1, 1, 2, 2, 3, 4, 5, 8, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 8, 5, 4, 3, 2, 2, 1, 1, 1, 0, 0]


8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
dummy_list.remove(200)

# Let's play: try the same with something which is not in the list to get the ValueError
dummy_list.remove(23)

ValueError: ignored

9) Remove the item at position x. x is any random integer

In [0]:
x=5
del dummy_list[x]

# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get
x=len(dummy_list)+3
del dummy_list[x]

IndexError: ignored

10) Let's clean everything clear the list and then print

In [0]:
dummy_list.clear()
print (dummy_list)

[]


# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy
n= np.linspace(-1.3,2.5,64)
n

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [0]:
n=2
a= np.array([1,2,3])
b=np.resize(a,3*3*n)
b

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3) Create an array of the first 10 odd integers.

In [0]:
n= np.arange(1,20,2)
n

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4) Find intersection of a and b

In [0]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
n=np.intersect1d(a,b)
n

array([2, 4])

5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10)
n=np.reshape(a,(-1,5))
n

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

6) Create a numpy array to list and vice versa

In [0]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b=np.array(a)
b


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [0]:
n=np.zeros(shape=(10,10))
n[:,0]=1
n[0,:]=1
n[:,9]=1
n[9,:]=1
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [0]:
n = np.zeros((8,8))
n[1::2,::2] = 1
n[::2,1::2] = 1
n



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])