In [0]:
import random
dummy_list=[]
for i in range(10):
  dummy_list.append(random.randrange(1,10))


In [4]:
print(dummy_list)

[8, 7, 2, 9, 4, 5, 2, 5, 5, 4]


In [5]:
dummy_list.reverse()
print(dummy_list)

[4, 5, 5, 2, 5, 4, 9, 2, 7, 8]


In [10]:
dummy_list_2=[2,200,16,4,1,0,9.45,45.67,90,12.01,12.-2,]
dummy_list.extend(dummy_list_2)
print (dummy_list)

[4, 5, 5, 2, 5, 4, 9, 2, 7, 8, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 10.0]


In [11]:
dummy_dict={i:dummy_list.count(i)
           for i in dummy_list}
print (dummy_dict)


{4: 3, 5: 3, 2: 3, 9: 1, 7: 1, 8: 1, 200: 1, 16: 1, 1: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 10.0: 1}


In [12]:
print(sorted(dummy_list))
print(sorted(dummy_list,reverse=True))


[0, 1, 2, 2, 2, 4, 4, 4, 5, 5, 5, 7, 8, 9, 9.45, 10.0, 12.01, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.01, 10.0, 9.45, 9, 8, 7, 5, 5, 5, 4, 4, 4, 2, 2, 2, 1, 0]


In [13]:
x=200
dummy_list.remove(x)
print(dummy_list)

[4, 5, 5, 2, 5, 4, 9, 2, 7, 8, 2, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 10.0]


In [14]:
x=80 dummy_list.remove(80)
print(dummy_list)


SyntaxError: ignored

In [15]:
dummy_list.pop(3)
print(dummy_list)


[4, 5, 5, 5, 4, 9, 2, 7, 8, 2, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 10.0]


In [16]:
dummy_list.pop(40)
print(dummy_list)


IndexError: ignored

In [18]:
import numpy as np
x=[]
for i in range (1,20,2):
  x.append(i)
x= np.array(x)
print(x)


[ 1  3  5  7  9 11 13 15 17 19]


In [25]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
sa=set(a)
sb=set(b)
c=sa.intersection(sb)
print (c)


{2, 4}


In [28]:
a=np.arange(10)
b=np.reshape(a,(2,5))
print (b)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [31]:
a=[1,2,3,4,5,6,7,8,9]
array=np.array(a)
print(array)
list =array.tolist()
list

[1 2 3 4 5 6 7 8 9]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
a=np.zeros([10,10],dtype=int)
a[0::9,:]=1
a[:,0::9]=1
print (a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [36]:
a=np.zeros([10,10],dtype=int)
a[0::2,::2]=1
a[1::2,1::2]=1
print (a)


[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]
