# Exercise - List

1) Create  any random list and assign it to a variable dummy_list

In [0]:
dummy_list=[i for i in range(10)]

2) print dummy_list

In [0]:
print(dummy_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


3) Reverse dummy_list and print

In [0]:
dummy_list.sort(reverse=True)
print(dummy_list)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [0]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values. 

In [0]:
from collections import Counter
dummy_dict=Counter(dummy_list)


Counter({4: 2, 2: 2, 1: 2, 0: 2, 9: 1, 8: 1, 7: 1, 6: 1, 5: 1, 3: 1, 200: 1, 16: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1})


6) print dummy_dict

In [0]:
print(dummy_dict)

Counter({4: 2, 2: 2, 1: 2, 0: 2, 9: 1, 8: 1, 7: 1, 6: 1, 5: 1, 3: 1, 200: 1, 16: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1})


7) Sort dummy_list in ascending order as well as descending order and print the changed lists 

In [0]:
print(sorted(dummy_list))
print(sorted(dummy_list,reverse=True))

[0, 0, 1, 1, 2, 2, 3, 4, 4, 5, 6, 7, 8, 9, 9.45, 12.01, 12.02, 16, 45.67, 90, 200]
[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 9, 8, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0, 0]


8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
dummy_list.remove(x)
print(dummy_list)

# Let's play: try the same with something which is not in the list to get the ValueError
dummy_list.remove(10)
print(dummy_list)

ValueError: ignored

9) Remove the item at position x. x is any random integer

In [0]:
print(dummy_list)
del dummy_list[4]
print(dummy_list)
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get

del dummy_list[25]

[9, 8, 7, 6, 4, 3, 2, 1, 0, 2, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
[9, 8, 7, 6, 3, 2, 1, 0, 2, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


IndexError: ignored

10) Let's clean everything clear the list and then print

In [0]:
dummy_list.clear()
print(dummy_list)

[]


# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy
print(np.linspace(-1.3,2.5,num=64))

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [0]:
x=np.array([1,2,3])
y=np.resize(x,3*x.shape[0])
print(y.reshape(3,3))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


3) Create an array of the first 10 odd integers.

In [0]:
print(np.arange(1,20,2))

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [0]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=set(a)& set(b)
print(np.array(list(c)))

[2 4]


5) Reshape 1d array a to 2d array of 2X5

In [0]:
a = np.arange(10)
print(a.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [0]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list(a)
print(type(a))
a=np.array(a)
print(type(a))


<class 'list'>
<class 'numpy.ndarray'>


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [0]:
zero_arr=np.zeros((10,10))
zero_arr[::9,:]=1
zero_arr[:,::9]=1
print(zero_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [0]:
checker=np.zeros((8,8))
checker[::2,1::2]=1
checker[1::2,::2]=1
print(checker)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
