<a href="https://colab.research.google.com/github/shuvankarroy/Assignment-2/blob/shuvankarroy/shuvankarroy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**"""List.ipynb - this exercise teaches you basic list manipulation."""**

---



###1) Create any random list and assign it to a variable dummy_list

In [0]:
import random
dummy_list = random.sample(range(1, 1000), 10)

### 2) print dummy_list

In [2]:
print(dummy_list)

[297, 838, 776, 927, 968, 28, 63, 579, 882, 938]


###3) Reverse dummy_list and print

In [3]:
dummy_list.reverse()
print(dummy_list)

[938, 882, 579, 63, 28, 968, 927, 776, 838, 297]


###4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list

In [4]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)

[938, 882, 579, 63, 28, 968, 927, 776, 838, 297, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


###5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values.

In [0]:
dummy_dict = {x:dummy_list.count(x) for x in dummy_list}

###6) print dummy_dict

In [6]:
print(dummy_dict)

{938: 1, 882: 1, 579: 1, 63: 1, 28: 1, 968: 1, 927: 1, 776: 1, 838: 1, 297: 1, 2: 1, 200: 1, 16: 1, 4: 1, 1: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


###7) Sort dummy_list in ascending order as well as descending order and print the changed lists

In [7]:
dummy_list.sort(reverse = False)
print(dummy_list)
dummy_list.sort(reverse = True)
print(dummy_list)

[0, 1, 2, 4, 9.45, 12.01, 12.02, 16, 28, 45.67, 63, 90, 200, 297, 579, 776, 838, 882, 927, 938, 968]
[968, 938, 927, 882, 838, 776, 579, 297, 200, 90, 63, 45.67, 28, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


###8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x = 200
dummy_list.remove(x)

###9) Remove the item at position x. x is any random integer

In [0]:
x = random.randint(0,len(dummy_list)-1)
dummy_list.remove(dummy_list[x])


###Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get

In [10]:
x = len(dummy_list) + 1
dummy_list.remove(dummy_list[x]) # will generate error

IndexError: ignored

### 10) Let's clean everything clear the list and then print

In [11]:
dummy_list.clear()
print(dummy_list)

[]


##"""Numpy Exercises : Numpy_Exercises.ipynb"""

---


###**import** numpy

In [0]:
import numpy as np 

###1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [14]:
np.linspace(-1.3, 2.5, num=64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

###2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [23]:
pattern = [1,2,3]
n = 1 + np.random.randint(10)
array1 = np.tile(pattern, n)
print(array1)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


###3) Create an array of the first 10 odd integers.

In [24]:
array2 = np.arange(1,20,2)
print(array2)

[ 1  3  5  7  9 11 13 15 17 19]


###4) Find intersection of a and b
###expected output array([2, 4])

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
intersect_ab = np.intersect1d(a,b)
print(intersect_ab)

[2 4]


#5) Reshape 1d array a to 2d array of 2X5

In [28]:
a = np.arange(10)
a = a.reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#6) Create a numpy array to list and vice versa

In [29]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np_a = np.array(a)
list_a = list(np_a)
print(np_a)
print(list_a)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


###7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [30]:
a = np.full(shape=(10,10), fill_value=0)
col = np.full(shape = (10,1),fill_value = 1)
row = np.full(shape = (1,12),fill_value = 1)
a = np.column_stack((col,a))
a = np.column_stack((a,col))
a = np.row_stack((a,row))
a= np.row_stack((row,a))
print(a)

[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]


###8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [31]:
checker = np.zeros((8,8),dtype=int)
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print(checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
