In [0]:
#1) Create any random list and assign it to a variable dummy_list
dummy_list=[100,300,200,500,400]
print(dummy_list)#2) print dummy_list
dummy_list.reverse()
print(dummy_list)#3) Reverse dummy_list and print
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list=dummy_list + dummy_list_2#4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list
print(dummy_list)
dummy_dict={}
k=2
for i in dummy_list:
  dummy_dict[i]=k*2
  k=k+1
print(dummy_dict)  #5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values.6) print dummy_dict
dummy_list.sort()#7) Sort dummy_list in ascending order as well as descending order and print the changed lists
print(dummy_list)
dummy_list.sort(reverse=True)
print(dummy_list)
x=200#8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.
p=0
j=0
for j in dummy_list:
  if j==x :
    dummy_list.remove(j)
    break
  else:
    j=j+1
    p=p+1
  
if p==len(dummy_list):
  print("ValueError")
else:
  print(dummy_list)
  
x=14#9) Remove the item at position x. x is any random integer
if(x>len(dummy_list)):
  print("Out of Range")
else:
  del dummy_list[x]
print(dummy_list)
del dummy_list[:]#10) Let's clean everything clear the list and then print
print(dummy_list)


  
  



[100, 300, 200, 500, 400]
[400, 500, 200, 300, 100]
[400, 500, 200, 300, 100, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
{400: 4, 500: 6, 200: 16, 300: 10, 100: 12, 2: 14, 16: 18, 4: 20, 1: 22, 0: 24, 9.45: 26, 45.67: 28, 90: 30, 12.01: 32, 12.02: 34}
[0, 1, 2, 4, 9.45, 12.01, 12.02, 16, 45.67, 90, 100, 200, 200, 300, 400, 500]
[500, 400, 300, 200, 200, 100, 90, 45.67, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]
[500, 400, 300, 200, 100, 90, 45.67, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]
[500, 400, 300, 200, 100, 90, 45.67, 16, 12.02, 12.01, 9.45, 4, 2, 1]
[]


In [1]:
import numpy as np#Import numpy
a=np.array([100,200,300])
print(a)
print(type(a))

b=np.array([[10,20,30],[40,50,60]]) #Create numpy arrays
print(b.shape)
print(b[0,0],b[0,1],b[1,0])
a=np.zeros(shape=(2,2))#Some basic functions for creating arrays
b=np.ones(shape=(3,3))
c=np.eye(2)
d=np.full(shape=(3,3),fill_value=5)
e=np.random.random((2,2))
print('a',a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)
a==np.arange(10) #execute and understand
b==np.linspace(0,10,num=6)
print(a)
print(b)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])#Array Indexing
b = a[:2, 1:3]
print(a[0,1])
b[0,0]=77
print(a[0,1])
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])#slicing
row_r1 = a[1, :]    
row_r2 = a[1:2, :]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)


x=np.array([[1,2],[3,4]])#Arithmetic operations
print(np.sum(x))
print(np.sum(x,axis=0))#sum of each column
print(np.sum(x,axis=1))#sum of each row
b=np.arange(10)#Boolean Mask use
print(b)
mask=b%2!=0
print(mask)
print(b[mask])
mod_b=b
mod_b[mask]=-1
print(mod_b)
a=np.arange(9).reshape(3,3)#swapping 2 colums
print(a)
print(a[:,[1,0,2]])
a=np.arange(9).reshape(3,3)#swapping 2 rows
print(a)
print(a[[1,0,2],:])



[100 200 300]
<class 'numpy.ndarray'>
(2, 3)
10 20 40
a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.58957867 0.78449677]
 [0.17984702 0.68954991]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
10
[4 6]
[3 7]
[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.


In [2]:



import numpy as np#Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions
A=np.linspace(-1.3,2.5,64)
print(A)





n=int(input())# Generate an array of length 3n filled with the cyclic pattern 1, 2, 3
B=np.array([1,2,3])
B=np.resize(B,3*n)
print(B)





b1=np.arange(1,20,2)#Create an array of the first 10 odd integers.
print(b1)





a=np.array([1,2,3,2,3,4,3,4,5,6])#Find intersection of a and b
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)





a1=np.arange(10)# Reshape 1d array a to 2d array of 2X5
print(a1)
a1=a1.reshape(2,5)
print(a1)





a2=[1,2,3,4,5,6,7,8,9]#conversion
a2=np.array(a2)#numpy list to array
print(a2)
a2.tolist()#numpy array to list
print(a2)





a3=np.ones(shape=(10,10))# Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.
a3[1:9,1:9]=0
print(a3)





a4=np.ones(shape=(8,8))#Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.
a4[::2,1::2]=0
a4[1::2,::2]=0
print(a4)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]
6
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
[ 1  3  5  7  9 11 13 15 17 19]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.