In [20]:
import numpy as np#Import numpy
a=np.array([100,200,300])
print(a)
print(type(a))

b=np.array([[10,20,30],[40,50,60]]) #Create numpy arrays
print(b.shape)
print(b[0,0],b[0,1],b[1,0])
a=np.zeros(shape=(2,2))#Some basic functions for creating arrays
b=np.ones(shape=(3,3))
c=np.eye(2)
d=np.full(shape=(3,3),fill_value=5)
e=np.random.random((2,2))
print('a',a)
print('b',b)
print('c',c)
print('d',d)
print('e',e)
a==np.arange(10) #execute and understand
b==np.linspace(0,10,num=6)
print(a)
print(b)

x=np.array([[1,2],[3,4]])#Arithmetic operations
print(np.sum(x))
print(np.sum(x,axis=0))#sum of each column
print(np.sum(x,axis=1))#sum of each row
b=np.arange(10)#Boolean Mask use
print(b)
mask=b%2!=0
print(mask)
print(b[mask])
mod_b=b
mod_b[mask]=-1
print(mod_b)
a=np.arange(9).reshape(3,3)#swapping 2 colums
print(a)
print(a[:,[1,0,2]])
a=np.arange(9).reshape(3,3)#swapping 2 rows
print(a)
print(a[[1,0,2],:])






[100 200 300]
<class 'numpy.ndarray'>
(2, 3)
10 20 40
a [[0. 0.]
 [0. 0.]]
b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c [[1. 0.]
 [0. 1.]]
d [[5 5 5]
 [5 5 5]
 [5 5 5]]
e [[0.30145182 0.0820182 ]
 [0.64159066 0.576512  ]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
10
[4 6]
[3 7]
[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
