In [0]:
dummy_list=[12,54,98,34,90,7.46]

In [0]:
print(dummy_list)

[12, 54, 98, 34, 90, 7.46]


In [0]:
dummy_list.reverse()
print(dummy_list)

[7.46, 90, 34, 98, 54, 12]


In [0]:
dummy_list_2=[2,200,16,4,1,0,9.45,45.67,90,12.01,12.02]
dummy_list=dummy_list+dummy_list_2
print(dummy_list)

[7.46, 90, 34, 98, 54, 12, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_dict={x:dummy_list.count(x) for x in dummy_list}

In [0]:
print(dummy_dict)

{7.46: 1, 90: 2, 34: 1, 98: 1, 54: 1, 12: 1, 2: 1, 200: 1, 16: 1, 4: 1, 1: 1, 0: 1, 9.45: 1, 45.67: 1, 12.01: 1, 12.02: 1}


In [0]:
dummy_list.sort()
print(dummy_list)
dummy_list.sort(reverse=True)
print(dummy_list)

[0, 1, 2, 4, 7.46, 9.45, 12, 12.01, 12.02, 16, 34, 45.67, 54, 90, 90, 98, 200]
[200, 98, 90, 90, 54, 45.67, 34, 16, 12.02, 12.01, 12, 9.45, 7.46, 4, 2, 1, 0]


In [0]:
dummy_list.remove(200)
print(dummy_list)

[98, 90, 90, 54, 45.67, 34, 16, 12.02, 12.01, 12, 9.45, 7.46, 4, 2, 1, 0]


In [0]:
del dummy_list[10]
print(dummy_list)

[98, 90, 90, 54, 45.67, 34, 16, 12.02, 12.01, 12, 7.46, 4, 2, 1, 0]


In [0]:
dummy_list.clear()
print(dummy_list)

[]


Numpy Exercises

In [0]:
import numpy as np

In [7]:
a=np.linspace(-1.3,2.5,64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [13]:
a=np.full(shape=(3,3), fill_value=(1,2,3))
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
a=np.arange(1,20,2)
print(a)



[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
x=np.intersect1d(a,b)
print(x)

[2 4]


In [20]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a.tolist()
print(a)
a=np.array(a)
print(a)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [27]:
x = np.random.randint(1,size=(10,10))
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [28]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
