In [0]:
import numpy as np # import numpy

Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [12]:
a = np.linspace(-1.3,2.5,num=64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [3]:
a = np.array([])
n = 2 #for n =2
for j in range(0,3*n):
    b = np.arange(1,4)
    a = np.concatenate([a,b]).astype(int)
print(a)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


Create an array of the first 10 odd integers.

In [6]:
n = 19 #10th odd integer
a = np.linspace(1,19,num=10).astype(int)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


Find intersection of a and b

In [8]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) #Given
b = np.array([7,2,10,2,7,4,9,4,9,8]) #Given
c = np.intersect1d(a,b)
print(c)

[2 4]


 Reshape 1d array a to 2d array of 2X5

In [10]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

Create a numpy array to list and vice versa

In [20]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
res = np.array([a])
print(res)
print(type(res))
c = res.tolist()
print(c)
print(type(c))

[[1 2 3 4 5 6 7 8 9]]
<class 'numpy.ndarray'>
[[1, 2, 3, 4, 5, 6, 7, 8, 9]]
<class 'list'>


In [11]:
a = np.zeros((10,10),dtype=int)
b = np.ones((10,1),dtype=int) #vertical
c = np.ones((1,12),dtype=int) #horizontal
res = np.concatenate([b,a],axis=1)
res = np.concatenate([res,b],axis=1)
res = np.concatenate([c,res],axis=0)
res = np.concatenate([res,c],axis=0)
print(res)

[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]


Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [21]:
a = np.zeros((8,8),dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
