In [0]:
dummy_list=[1,2,3,4,5,6,7,8]

In [12]:
print(dummy_list)

[1, 2, 3, 4, 5, 6, 7, 8]


In [13]:
dummy_list.reverse()
print(dummy_list)

[8, 7, 6, 5, 4, 3, 2, 1]


In [14]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list += dummy_list_2
print(dummy_list)

[8, 7, 6, 5, 4, 3, 2, 1, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_dict={}

In [0]:
y=[]
for i in dummy_list:
  if(i not in y):
    y.append(i)
    dummy_dict[i] = 1
  else:
    dummy_dict[i] += 1

In [17]:
print(dummy_dict)

{8: 1, 7: 1, 6: 1, 5: 1, 4: 2, 3: 1, 2: 2, 1: 2, 200: 1, 16: 1, 0: 1, 9.45: 1, 45.67: 1, 90: 1, 12.01: 1, 12.02: 1}


In [18]:
dummy_list.sort()
dummy_list.reverse()
print(dummy_list)

[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 8, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0]


In [19]:
x = 200
dummy_list.remove(y.index(x))
print(dummy_list)


[200, 90, 45.67, 16, 12.02, 12.01, 9.45, 7, 6, 5, 4, 4, 3, 2, 2, 1, 1, 0]


In [20]:
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get
 dummy_list.remove(len(dummy_list))

ValueError: ignored

In [21]:
dummy_list.clear()
print(dummy_list)

[]


In [22]:
import numpy as np #import numpy
arr = np.linspace(-1.3,2.5,64)
print(arr)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [23]:
arr = np.array([1,2,3]*3)
print(arr)

[1 2 3 1 2 3 1 2 3]


In [24]:
odd = np.arange(10)
odd=odd[odd%2!=0]
print(odd)

[1 3 5 7 9]


In [25]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)
print(c)

[2 4]


In [26]:
a = np.arange(10)
a = a.reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_a = np.array(a)
print(arr_a)

list_a = list(arr_a)

print(list_a)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
z = np.zeros((10,10))
# print(z)

z[:,0]=1
z[:,9]=1
z[0,:]=1
z[9,:]=1

print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
