**ASSIGNMENT 2:**


3. NUMPY EXERCISES

In [0]:
import numpy as np

1).Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [4]:
a = np.linspace(-1.3,2.5,64)
print(a)


[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


3).Create an array of the first 10 odd integers.

In [10]:
a=[]
for i in range(1,20): 
  if i%2!=0:
     a.append(i)
  if (len(a)!=20):
         i+=1
print(a)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


4) Find intersection of a and b

In [13]:
c = [ ]

#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#if (for i in a: for j in b: if i==j: c.append[i] i++)
print (c)

list (set(a) & set(b))

[]


[2, 4]

5) Reshape 1d array a to 2d array of 2X5


In [36]:
a = np.arange(10)
print(a)
#b = a.reshape(a.shape[-10:5],5)
b = a.reshape(2,5)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa


In [42]:
a = ([1, 2, 3, 4, 5, 6, 7, 8, 9])
#print(a.tolist())
print(list(a))
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = np.asarray(a)
d = np.array(a)
print(d)
b

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [46]:
z = np.ones((12,12))
#z = zeros((12,12))
#a = ones(12)
#b = ones((,10))
#v = [a,b,z,b,a]  */
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8).Write a Python program to create a 8*8 matrix and fill it with a checkerboard pattern.

In [48]:
x=np.ones((3,3))
print("Checkerboard pattern:")
x=np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**1) LISTS**

1) Create any random list and assign it to a variable dummy_list

In [0]:
import random
dummy_list = random.sample(range(20),7)

2) print dummy_list


In [69]:
print(dummy_list)


[0, 0, 0, 1, 1, 2, 2, 4, 4, 6, 8, 9.45, 9.45, 11, 12, 12.01, 12.01, 12.02, 12.02, 14, 16, 16, 17, 45.67, 45.67, 90, 90, 200, 200]


3)Reverse dummy_list and print

In [70]:
print(dummy_list.reverse())

None


4) Add the list dummy_list_2 to the previous dummy_list and now print dummy_list


In [71]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
dummy_list.extend(dummy_list_2)
print(dummy_list)



[200, 200, 90, 90, 45.67, 45.67, 17, 16, 16, 14, 12.02, 12.02, 12.01, 12.01, 12, 11, 9.45, 9.45, 8, 6, 4, 4, 2, 2, 1, 1, 0, 0, 0, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


5) Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values.

6) print dummy_dict

In [72]:
import collections
cntr = collections.Counter(a)
#j = []
dummy_dict = cntr
#for i in cntr.values:
#  j.append(i)
  
#dummy_dict = {a[i]: a[i+1] for i in range(0, len(a), 2)}  
print(dummy_dict)

Counter({1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1})


7) ) Sort dummy_list in ascending order as well as descending order and print the changed lists


In [0]:
dummy_list.sort()
print(dummy_list)
dummy_list.sort(reverse=True)
print(dummy_list)

NameError: ignored

8) Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

In [0]:
x= 200
for i in list:
  if i==5:
    dummy_list.remove(x)
    

9) Remove the item at position x. x is any random integer

In [0]:
#similar to deleting by index,i.e., del[a : b]

10) Let's clean everything clear the list and then print

In [0]:
dummy_list.clear()