In [0]:
#Create any random list and assign it to a variable dummy_list
dummy_list=[1,2,3,4,6,4,7,8,9,9]

In [8]:
print(dummy_list)

[1, 2, 3, 4, 6, 4, 7, 8, 9, 9]


In [9]:
#Reverse dummy_list and print
print(dummy_list[::-1])

[9, 9, 8, 7, 4, 6, 4, 3, 2, 1]


In [10]:
#Add the list dummy_list_2 to the previous dummy_list and now print dummy_list
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
print(dummy_list+dummy_list_2)

[1, 2, 3, 4, 6, 4, 7, 8, 9, 9, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
#Create a dictionary named dummy_dict which contains all the elements of dummy_list as keys and frequency as values.
dummy_dict = {}
for i in dummy_list:
        dummy_dict[i] = dummy_list.count(i)

In [12]:
print(dummy_dict)

{1: 1, 2: 1, 3: 1, 4: 2, 6: 1, 7: 1, 8: 1, 9: 2}


In [13]:
#Sort dummy_list in ascending order as well as descending order and print the changed lists
print(sorted(dummy_list))
print(sorted(dummy_list,reverse=True))

[1, 2, 3, 4, 4, 6, 7, 8, 9, 9]
[9, 9, 8, 7, 6, 4, 4, 3, 2, 1]


In [0]:
#Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.
x = 9
#x=200
if x in dummy_list:
  dummy_list.remove(x)
elif x not in dummy_list:
  raise ValueError("Element not in list")
# Let's play: try the same with something which is not in the list to get the ValueError

In [15]:
#Remove the item at position x. x is any random integer
import random
x=random.randrange(0,len(dummy_list))
#x=random.randrange(len(dummy_list)+1,len(dummy_list)+10)
print(x)
dummy_list.remove(dummy_list[x])
print("the element at",x,"has been deleted new list is", dummy_list)
# Let's play: try doing the same with x > len(dummy_list) + 1 and see what you get

0
the element at 0 has been deleted new list is [2, 3, 4, 6, 4, 7, 8, 9]


In [16]:
#Let's clean everything clear the list and then print
dummy_list.clear()
print(dummy_list)

[]


**NUMPY** **EXERCISES**

In [17]:
#Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions
import numpy as np #import numpy
a=np.linspace(-1.3,2.5,num=64)
a

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

In [18]:
#Generate an array of length 3n filled with the cyclic pattern 1, 2, 3
n=9
#use different values of n
a=np.arange(1,4)
a=np.resize(a,3*n)
a

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3])

In [19]:
#Create an array of the first 10 odd integers.
odd=np.arange(1,20,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
#Find intersection of a and b
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [21]:
#Reshape 1d array a to 2d array of 2X5
a = np.arange(10)
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
#Create a numpy array to list and vice versa
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(a)
np.array(a)
a.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
#Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.
arr = np.zeros((10, 10),dtype=int)
arr[0:10,::9] = 1
arr[::9,0:10] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
#Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])