# Excercise- Lists

In [0]:
x_List = [ 227, 125, 112, 123 ]
dummy_list = x_List


In [2]:
  print(dummy_list)

[227, 125, 112, 123]


In [0]:
dummy_list[::-1]


In [3]:
dummy_list_2 = [2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]
mergedlist = dummy_list + dummy_list_2
print(mergedlist)


[227, 125, 112, 123, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [0]:
dummy_dict={z: mergedlist.count(z) for z in mergedlist}

In [5]:
print(mergedlist)

[227, 125, 112, 123, 2, 200, 16, 4, 1, 0, 9.45, 45.67, 90, 12.01, 12.02]


In [11]:
mergedlist.sort() #ascending
print("Ascending- ",mergedlist)

mergedlist.sort(reverse=True)
print("Descending- ",mergedlist)

Ascending-  [0, 1, 2, 4, 9.45, 12.01, 12.02, 16, 45.67, 90, 112, 123, 125, 200, 227]
Descending-  [227, 200, 125, 123, 112, 90, 45.67, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


In [0]:
r= 200
mergedlist.remove(r)

In [16]:
x=4
del mergedlist [x]
print("Deletion-",mergedlist)

Deletion- [227, 125, 123, 112, 16, 12.02, 12.01, 9.45, 4, 2, 1, 0]


In [19]:
mergedlist.clear()
print("Cleared List", mergedlist)

Cleared List []


# NUMPY EXERCISE

In [25]:
import numpy as np #import numpy
a = np.linspace(-1.3,2.5, 64)
print(a)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [28]:
n=4
a = np.array([1,2,3])
b= np.resize(a, 3*n)
b


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
x =np.intersect1d(a,b)
x


array([2, 4])

In [32]:
a = np.arange(10).reshape(2,5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
a=[1,2,3,4,5]
a=np.array(a)
print('List to array',a)
c=a.tolist()
print('Array to list',c)

List to array [1 2 3 4 5]
Array to list [1, 2, 3, 4, 5]


In [37]:
a= np.zeros(shape=(10,10))
a[0,:]=1
a[:,0]=1
a[9,:]=1
a[:,9]=1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [44]:
a=np.zeros(shape=(8,8))
a[1::2,::2]=1
a[::2,1::2]=1
print('Checkboard Pattern\n',a)

Checkboard Pattern
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
